### ISSUE TITLE
TypeError: connect() got an unexpected keyword argument 'project'

### ISSUE THREAD

**Issue by dmonroy** [Crunch-io/scrunch#1]
When trying to connect with a specific project (as specified in docs/introduction.md) it fails because pycrunch.connect doesn't accept the `project` argument.
```
In [1]: import pycrunch
   ...: site = pycrunch.connect(
   ...:     user="me@mycompany.com", 
   ...:     pw="yourpassword", 
   ...:     site_url="https://app.crunch.io/api/",
   ...:     project="US Election"
   ...: )
   ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-21190621df99> in <module>()
      4     pw="yourpassword",
      5     site_url="https://app.crunch.io/api/",
----> 6     project="US Election"
      7 )

TypeError: connect() got an unexpected keyword argument 'project'
```

Seems like there are stuff on yougov/pycrunch that is not present in Crunch-io/pycrunch:
- https://github.com/yougov/pycrunch/blob/d2b7cef1eb5d13c8b5f1644c3a89361d71829727/pycrunch/__init__.py#L248
- https://github.com/Crunch-io/pycrunch/blob/a9dc7f203a08e6930dfcbe08095ca8c92e055273/pycrunch/__init__.py#L219

Are we going to move this to pycrunch? or it has to be part of the scrunch project?

**Comment by nealrichardson** [comment]
`connect` is about authentication. "project" has no place there.
