### ISSUE TITLE
Support changing weight using ds.change_settings()

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#101]
Trying to change the `weight` using `ds.change_settings()` returns the following a `ValueError`:

```python
>>> ds.change_settings(weight='weights_GB18')
ValueError: Invalid or read-only settings: weight
```

Assuming this is the right place to want to do this (`weight` is included in the attributes returned by looking at `ds.settings`) we need this to be made available here.

Related to this, when checking `ds.settings`, if there is a weight applied the URL of the weight variable is returned. It would be better if for scrunch users the alias of that variable was returned instead.

```
>>> ds.settings
{u'min_base_size': 0,
 u'viewers_can_change_weight': True,
 u'viewers_can_export': False,
 u'viewers_can_share': True,
 u'weight': u'https://app.crunch.io/api/datasets/e9637cc3c64d4273b2b63478e555fbd5/variables/000018/'}
```

**Comment by xbito** [comment]
Managing weights is part of an effort that is not yet scheduled. Even though the weight is currently available through the settings it is not the intention to allow setting it through that API. I'm going to close this one for now, but we should have news soon regarding weights.
