### ISSUE TITLE
make scrunch usable for packages

### ISSUE THREAD

**Issue by skriems** [Crunch-io/scrunch#103]
If scrunch should be usable for packages we need to start making releases and this also concerns pycrunch. Adding the scrunch repo to a requirements file currently installs pycrunch from pypi which is not compatible with our current code.

Until then we could just let the pycrunch repo get pulled by the setup.py file instead of the pypi version...

**Comment by xbito** [comment]
With the upload of pycrunch to pypi this should be solved now.
