### ISSUE TITLE
create_numeric

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#111]
Add a `create_numeric` method for adding a new numeric based on a derived expression.

```python
new_var = ds.create_numeric(
    alias='monthly_rent', 
    name='Monthly rent',
    description='Rent paid per month',
    notes='All UK adults',
    filter='region == 1',
    expression='(weekly_rent * 52) / 12'
)
```

The `filter` argument is important because a logical exclusion can't be built into the `expression`.

**Comment by xbito** [comment]
My only change would be to use the argument "derivation" instead of "expression" since that is closer to the language that Crunch actually uses?

@jamesrkg also, what's that filter? ah you mean apply a filter before doing the computation so it doesn't fill all rows? Is that supported @jjdelc?

**Comment by jamesrkg** [comment]
@xbito `derivation` - good. `expression` felt wrong but I couldn't put my finger on why at the time, and yes, `filter` is needed so that the derivation can be applied to a subset of rows if needed, otherwise there won't be any way to achieve that.

**Comment by jjdelc** [comment]
This is a derived variable as well with an arithmetic derivation. That is Ok but when creating variables it is not possible to indicate a filter. The new variable evaluates the function on all the column, not only on a selection of rows.

Your `monthly_rent` variable would have the value `(weekly_rent * 52) / 12` for all values, if it is missing on `monthly_rent` it will be missing on the new variable as well, but you cannot have the formula apply to only a few rows.

When you make queries over it, you can apply the filter you want and consider only those rows.

**Comment by jamesrkg** [comment]
@jjdelc understood.
