### ISSUE TITLE
(derived) Bind categorical variables into a categorical_array

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#113]
After creating a number of categorical variables (`var1, var2, var3, var4`) we need some way to bind them into a `categorical_array`.

```python
new_var = ds.bind_categorical_array(
    alias='purchases', 
    name='Purchases at department stores',
    description='What purchases did you make at each of these department stores?',
    notes='All UK adults',
    subvariables=[
        {'variable': var1, 'alias': 'purchases_1', 'name': 'Macy's'},
        {'variable': var2, 'alias': 'purchases_2', 'name': 'JCPenney'},
        {'variable': var3, 'alias': 'purchases_3', 'name': 'Khol's'},
        {'variable': var4, 'alias': 'purchases_4', 'name': 'Target'}
)
```

The `alias` of each `subvariable` should be optional, and if not given should be derived automatically by concatenating the name of the array with `_N` where `N` is the non-`0`-based item number in the `subvaraibles` list (as is done explicitly in the above example).

The `name` of each `subvariable` should also be option, and if not given should default to the `name` of the variable in that position.

Given the above default options the `subvariables` argument should be able to take a list of variables as well as a list of dicts such that the following shorthand is possible:

```python
new_var = ds.bind_categorical_array(
    alias='purchases', 
    name='Purchases at department stores',
    description='What purchases did you make at each of these department stores?',
    notes='All UK adults',
    subvariables=[var1, var2, var3, var4]
)
```

Similarly, in this form a list of strings representing variable aliases should also be possible:

```python
new_var = ds.bind_categorical_array(
    alias='purchases', 
    name='Purchases at department stores',
    description='What purchases did you make at each of these department stores?',
    notes='All UK adults',
    subvariables=['macys', 'jcpenney', 'khols', 'target']
)
```

**Comment by jjdelc** [comment]
There are two ways to do this, but we'll want to take the derived array route so we don't alter the state of the variables used.

This will be the case of creating a new variable with `derivation` like this:
```
{
  function: array,
  args: [{
    function: select,
    args: [{
      map: {subvariables map}   
    }]
  }, {value: [order of subvars]}]
}
```

That will create a categorical array as long as the subvariables categories do not specify a `selected` attribute.

**Comment by xbito** [comment]
@jjdelc 2 questions, are you ok then with the proposal?
Second, what's going to be in {subvariables map} exactly? And [order of subvars] will be a list of what?

**Comment by jjdelc** [comment]
Since all the variables that scrunch creates are derived variables, they do not affect the current state of the dataset. That means that if you create catvar1, carvar2, catvar3 and then make an array with them, you dataset will have now catvar1, catvar2, catvar3 and array variable. The new array variable depends on those three variables.

Subvariable map would be a map like all other `select` functions always take a dictionary like this:
```
{
  designated_subvarid: {variable: var1_url},
  ...
}
```

And order of subvars is an array that contains the list of `designated_subvarid`s used in the array that indicates their order in the array.

The names and aliases of the new subvariables should go at the end of the expression like this:
```
{
  function: array,
  args: [{
    function: select,
    args: [{
      map: {subvariables map}   
    }]
  }, {value: [order of subvars]}],
  references: {
    name: array_name,
    alias: array_alias,
    subreferences: [
      {name: first_subvar_name, alias: first_subvar_alias},
      ...
    ]  
  }
}
```

**Comment by jamesrkg** [comment]
Refocusing this one to the derived use case as we have a material variable version of this now (#182).
