### ISSUE TITLE
(derived) Reorder subvariables in an array

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#115]
We need a way to reorder the subvariables in an array, something like:

```python
ds[array_alias].subvariables.reorder(subalias_1, subalias_4, subalias_2, subalias_3)
```

**Comment by jjdelc** [comment]
Similar to https://github.com/Crunch-io/scrunch/issues/114 there are two paths for this depending if the variable is derived or not.

To reorder a non derived, this is a PATCH on the `subvariables` attribute on the variable entity endpoint with the new order.

For a derived variable, it is necessary to PATCH the `derivation` on the variable entity endpoint with a new derivation expression indicating the variables in the desired order.

**Comment by xbito** [comment]
@alejandro-rivera is there a way to do this in the ordering API or shall we at least define the API here similar to the ordering behavior?

**Comment by jamesrkg** [comment]
Re-focusing this one onto derived arrays only, since we now have a separate ticket for material arrays (#206).

**Comment by mathiasbc** [comment]
subvariables can be reordered with: https://github.com/Crunch-io/scrunch/issues/206
Independent of the type of variable. So that method `reoder_variables` will do for this case as well.
