### ISSUE TITLE
(non-derived) Add subvariable to existing array

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#116]
In #114 we're looking at removing a subvariable from an array. Consequently we also need to think about adding a subvariable to an existing array (as opposed to creating a new array from scratch, as in #113).

Given we already have `create_categorical()` we can probably assume that the future subvariable already exists in the form of a standalone variable. (While this removes the need to cater for creating _and_ adding in one call,  does it impose unnecessary namespace demands on the new subvariable's `alias`/`name`?)

This means an approach such as the following might be possible:

```python
ds[array_alias].add_subvariable(subvariable=var1)
```

Alternatively it might be a good idea to allow _insertion_ so the position of the new subvariable in the subvariables catalog can be controlled (default `-1`), but this opens up a host of control mechanisms we only otherwise see in the dataset order, such as `insert`, `before` and `after` which we may want to avoid.
Those complications could be ignored in favor of leaving that to the subvariables reordering feature proposed in #115.

**Comment by jjdelc** [comment]
Same as #114 , the strategy takes two paths for non derived and derived variables.

On non derived, the new variables gets added to the `/subvariables/` catalog of the variable, and PATCH the index with the new variable added to it as a key.

On derived, it will be necessary to re-create the derivation expression including the new variable and PATCH to the entity endpoint with the updated `derivation` attribute.

**Comment by xbito** [comment]
@jjdelc In the case of the derived, the suggested operation would mean that we would end up with a variable outside (var1) and a new var created by the re-derivation? It is not actually moving something inside right? So we might need to also delete var1 first? Is that is going to cause problems if that variable is used anywhere else like filters/exclusion filter/etc?

**Comment by jjdelc** [comment]
@xbito all the variables that scrunch creates are derived variables, so they are projections of other variables. The rest of the dataset would(and should) remain untouched when a new array is created. The variables (or expressions, in the case of `case`) are references to existing data on the dataset and it doesn't change. 

The same fashion when removing subvariables from it or deleting the derived array variable, the dependencies remain untouched.

**Comment by jamesrkg** [comment]
Refocusing on the non-derived use case.
