### ISSUE TITLE
get_dataset by id should construct the URL of the dataset directly instead of using the datasets endpoint

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#119]
People store the dataset id that they created locally and then try to use it by just invoking scrunch.get_dataset and passing the id, unfortunately if the dataset is in a project this doesn't work. It demands that we pass either the project name or object.

I think we should allow to pass just the dataset id, and instead of doing a search in the datasets endpoint just construct the dataset url directly to then query the endpoint and construct the Dataset object.

**Comment by jjdelc** [comment]
If /search/ is not providing the right value or has ambiguous results, then for now we will have to just stitch strings together and trust that is that dataset URL.

**Comment by mathiasbc** [comment]
https://github.com/Crunch-io/scrunch/pull/125
