### ISSUE TITLE
Savepoint creation sometimes times out

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#120]
The operation of creating a savepoint sometimes timeout. There is a number of possibilities here:
- Allow the client to manipulate the max time to wait (currently we are using the default in pycrunch).
- Pass to the client the response in order to force them to handle the waiting time and decide what's the adequate waiting time and retry strategy.

If we do the latter we should do so in a 2 step operation where one version has the new behavior as optional and then the next release actually deprecates the previous behavior.

Assigning to Jj initially for any Crunch comments.

**Comment by nealrichardson** [comment]
We're fixing the savepoint creation not to timeout but instead return 202 Continue like other potentially slow requests do. Once that's resolved, use the standard Progress polling handler.

**Comment by xbito** [comment]
Ah @jjdelc and I were under the impression that that was the case already, but that pycrunch does have a timeout for the polling endpoint too and we were hitting that timeout. But if that is not the case then we shall wait until that's changed!

**Comment by xbito** [comment]
Seems to be related to this pull request then? https://github.com/Crunch-io/pycrunch/pull/25
