### ISSUE TITLE
create_group at specific location

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#122]
Creating a group and putting it in a specific position, while possible, feels clunky. The use case here is to fold a group of variables into a group but to keep that group in the position of the first of those variables, e.g.:

Before:

```
- q1
- q2_1
- q2_1
- q2_1
- q3
```

After:

```
- q1
+ q2
-- q2_1
-- q2_1
-- q2_1
- q3
```

The best way I can think to achieve this currently is:

```python
elements = ds.order['|'].keys()
group = 'q2'
variables = ['q2_1', 'q2_2', 'q2_3']
idx = elements.index(variables[0])
ds.order['|'].create_group(name=group, alias=variables)
ds.order['|'].insert(name=group, position=idx)
```

I'd prefer to be able to do this:

```python
group = 'q2'
variables = ['q2_1', 'q2_2', 'q2_3']
ds.order['|'].create_group(name=group, alias=variables, before=variables[0])
```

If this is acceptable then `after` and `position` should be added as well.

**Comment by xbito** [comment]
I think it is acceptable that create_group should follow the lead of the insert method and have position, before and after parameters. Will assign the work.

**Comment by skriems** [comment]
closing now but tests will be checked/added next week
