### ISSUE TITLE
feature/mr_in breaks direct subvariable referencing syntax

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#124]
The branch `feature/mr_in` throws an error on direct subvariable referencing syntax.

I've tried to reference a subvaraible by alias from both a `categorical_array` and a `multiple_response`, such as `'gornewGB_1 == 1'` where `gornewGB_1` is the alias of a subvariable within the variable `gornewGB`.

**Comment by xbito** [comment]
So this must be fixed now?
