### ISSUE TITLE
Counting multiple_response responses

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#126]
Here we want to know how many responses the user selected from a `multiple_response`. For example to test if more than three responses were selected: `my_mr.count() > 3`. The assumption here is of course that the `selected:true` subvariables are counted.

**Comment by xbito** [comment]
I see in the crunch docs that there is a "selected_depth" builtin function:

selected_depth Return a numeric column containing the number of selected categories in each row of the given array.

@jjdelc is that something we could use for this case? that is translate a: `my_mr.count() > 3` to a crunch expression that uses selected_depth(my_mr) > 3?

**Comment by mathiasbc** [comment]
@jamesrkg The function that Fernando points here makes reference to a per row count but `my_mr.count() > 3` seems like you are simple trying to see how many `subvariables` have a `selected=True` category ?

**Comment by jamesrkg** [comment]
@mathiasbc sorry I missed your question there - yes that's right. `selected_depth` is an odd name for this, though. `count` would be more obvious (though I'd understand if you want to stick with the API nomenclature for consistency.

**Comment by jamesrkg** [comment]
Just commenting here because I don't think #334 is relevant (any more) to this, but the above conversation suggests we're waiting for something before proceeding, which I don't believe is accurate. Let me know if I'm mistaken.
