### ISSUE TITLE
When counting array subvariable responses, restrict by subvariables

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#130]
This is related to #126 and #129.

When counting array subvariables by responses we want a way to restrict the subvariables we're including in the test. For example, for an array with 10 subvariables we might want to count how many of only five of the subvariables had any of the responses `[1, 2, 3]`.

I'm not sure what viable syntax for this would look like but for illustration purposes at least I'll suggest: `my_array.subvariables([1, 4, 5, 7, 9]).count([1, 2, 3])`.

Since array subvariables don't actually have `id`s like that, it would presumably also have to allow a list of subvariable `alias`es. Integers would map to subvariable's whose `alias` complies with the standard convention of subvariable `alias` names in the form `alias_N` where `N` is the integer given.

**Comment by mathiasbc** [comment]
Seems tricky, this is a mapping of a function to a subset of subvariable instances, perhaps a helper function ?
