### ISSUE TITLE
Categoricals are sending bad expression

### ISSUE THREAD

**Issue by jjdelc** [Crunch-io/scrunch#136]
Expressions using the `case` function are sending an extra `true` parameter on the function's `args'. This will get 400 every time.
![page-shot-2017-5-26 valueerror_ invalid expression_ true](https://cloud.githubusercontent.com/assets/59393/26510605/b697ddda-4223-11e7-9cc1-98cdb7968dc0.png)

**Comment by mathiasbc** [comment]
@jjdelc: I can't find where this is coming from. It's most likely from `create_multiple_response` but it's not reproducible with the codebase in `master`. I got the following:

```
{  
   'element':'shoji:entity',
   'body':{  
      'notes':'',
      'name':'issue112',
      'alias':'issue112',
      'derivation':{  
         'args':[  
            {  
               'args':[  
                  {  
                     'map':{  
                        '0001':{  
                           'args':[  
                              {  },
                              {  }
                           ],
                           'references':{  
                              'name':'var equal',
                              'alias':'issue112_1'
                           },
                           'function':'case'
                        },
                        '0002':{  
                           'args':[  
                              {  },
                              {  }
                           ],
                           'references':{  },
                           'function':'case'
                        }
                     }
                  },
                  {  
                     'value':[  
                        '0001',
                        '0002'
                     ]
                  }
               ],
               'function':'select'
            }
         ],
         'function':'array'
      },
      'description':''
   }
}
```

**Comment by jjdelc** [comment]
I'll look again the error report. 
The user agent indicated pycrunch as the client and I don't think we have users using pycrunch directly for their scripts?

**Comment by jjdelc** [comment]
Looks like the `case` expression is bring built here: https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L1469.

From what that function does is only `.append` the parsed rules to the `case` expr args. so those rules were parse here: https://github.com/Crunch-io/scrunch/blob/master/scrunch/expressions.py#L464

Probably the user sent something in their expression that caused the expression to be parsed as `True` and then that got appended on the expr `args` causing this.

**Comment by mathiasbc** [comment]
@jjdelc We are thinking this must me some direct manipulation of the payload but unlikely to come from scrunch. Speaking of which, what can we do on Scrunch to set the client to scrunch. So the logs show the correct client name.

**Comment by mathiasbc** [comment]
There are no further incidences like this from the Scrunch side, so I will assume this was someone directly using Pycrunch.
