### ISSUE TITLE
Add ability to set fieldwork dates

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#144]
Using the GUI it's possible to set the fieldwork dates in the dataset properties. We need a way to do this manually or to provide a variable on which it should automatically be based.

**Comment by xbito** [comment]
@jamesrkg are you referring to the Start Date and End Date fields? Those are referential dates, we can definitively control them now in scrunch dataset.start_date and dataset.end_date are readable and can be edited using the .edit method.

**Comment by jamesrkg** [comment]
Thanks @xbito , sorry I wasn't aware.
