### ISSUE TITLE
Add before/after kwargs to Group.move()

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#146]
We want to be able to move a group into a position relative to another group or variable, e.g.:

```python
ds.order['|System|Timing'].move(path='|Excluded', after='endtime')
```

**Comment by skriems** [comment]
@jamesrkg are you sure this is not working. IIRC I already implemented that in https://github.com/Crunch-io/scrunch/pull/143

**Comment by xbito** [comment]
Seems like Sebastian is right. It is done already.
