### ISSUE TITLE
Material Joins

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#149]
Implement material joins. That is joins that don't link 2 datasets, instead they bring over the data and it is materialized in the target dataset.

**Comment by mathiasbc** [comment]
@xbito The code for [joins](https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L1966-L2027) looks good to me. The documentation only exposes this current implementation for Joins; see (http://docs.crunch.io/#merging-and-joining-datasets).

The documentation even says that it is an experimental feature and I bet there is a lot of checks behind the scenes. Perhaps we could implement a fake join, importing variables, appending, merging or a combination of those but I don't know if it's the right thing to do.

**Comment by mathiasbc** [comment]
@jjdelc Any ideas ?

**Comment by jjdelc** [comment]
We should use t he `adapt` method that's explained in the docs. It allows to select which variables and even filtered rows to bring in.

It looks like the linked joins code does just this currently.

**Comment by xbito** [comment]
I think there has been a misunderstanding here then. Jamie was under the impression that the current implementation of Joins were virtual, but turns out they are actually materialized already. He mentioned:

> The scenario we have currently is that to join weights generated outside of Crunch we'd need to upload them to a new dataset and perform a join between the two but then the 'weights only' dataset would need to persist because the join was virtual. That seems wasteful (2 datasets instead of 1) and dangerous (someone might delete the weights ds)

But if I understand correctly then, actually that second dataset doesn't need to persist then. Though that whole use-case may become easier if we could provide a way to add a column with data to a dataset. That should also be possible right @jjdelc though probably worth implementing a helper?

**Comment by jjdelc** [comment]
In the API it is possible to add a new column with data via normal variable creation, just need to specify the values for it. It can be either a single value or a column that has to be the size of the dataset.
The example here http://docs.crunch.io/#2-add-variable-definitions-and-column-data shows how to do it. 

Note that in case of giant datasets, sending the full column with values may be a problem. If no values are provided then {?: -1} will be used by default.
