### ISSUE TITLE
Integration of derived variables

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#150]
Add a way so we can ask Crunch to integrate (materialize) derived variables.

**Comment by skriems** [comment]
@jjdelc as mathias I'm also not 100% sure if this is covered by the docs. I'm going to test this out with `cast`ing or `copy`ing a derived variable but if you have any more insight, let me know.

**Comment by jjdelc** [comment]
We need to formalize support on the API for this. I have a ticket to work on this and will report.

**Comment by xbito** [comment]
I see a pull request for the docs now: https://github.com/Crunch-io/apidocs/pull/134/files

**Comment by jjdelc** [comment]
Yes, I hope this changes go out this week. In pycrunch it will be same as `variable_resource.edit(derived=False)`
