### ISSUE TITLE
Order Hierarchy API within projects

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#152]
Using rcrunch it's possible to create a project within another project, though I'm not sure this is possible using the web app.

Here's some code provided by Brian Law:

```r
# assume that 'ds' is the dataset you want to move
proj <- session()$projects$Discovery
datasets(proj) <- ds
ordering(datasets(proj))[['Omnibus projects']] <- union(entities(ordering(datasets(proj))[['Omnibus projects']]), self(ds))
```

We need access to this functionality, e.g.:

* Create a project within an existing project
* Manage sub-projects (owners, members, name, etc.)
* Get a dataset that's in a sub-project
* Move datasets to/from sub-projects

**Comment by jjdelc** [comment]
I think we have a nomenclature situation here. Crunch does not support projects inside projects. 

What is supported is grouping of the datasets inside a project, just like we support grouping variables, the same `shoji:order` format is used to make "folders" for the datasets that belong to a project.

**Comment by jamesrkg** [comment]
Thanks for clarifying @jjdelc .
