### ISSUE TITLE
Convert categorical to numeric

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#154]
Using the app it's possible to convert a categorical to a numeric. We'd like to be able to do this using scrunch.

When doing this with the app we're shown an example of what a summary of a numeric version of the variable would look like before converting it. It would be handy to be able to access this summary as well (without/before creating the numeric version).

**Comment by jjdelc** [comment]
We do this in the API using the cast function. For derived variables we will want to use the `cast` function. We can just wrap an expression like so:

```
{
  function: cast,
  args: [
    {variable: var_url}
  ]
}
```
OR

```
{
  function: cast,
  args: [
    {original_expression}
  ]
}
```

Note that we would need to either PATCH to replace the current variable with the new casted variable or POST to create a new variable with the casted value. Creating a new one will mean that the original categorical still lives and changes to it will reflect on the new one, I think we want to take this path as it will also not break in case that the categorical in question has any derivations.

**Comment by jamesrkg** [comment]
I would prefer to POST rather than PATCH as well. Typically we'd want an alternate-typed variable in addition to the original.

**Comment by jjdelc** [comment]
I want to note that this method does not work for datetime variables, we have different functions to "cast" datetimes that depend on the resolusion on or a date mask. So just make sure that we put a check that neither both the original or target type are datetimes.

**Comment by mathiasbc** [comment]
http://docs.crunch.io/#cast

**Comment by mathiasbc** [comment]
I am trying to implement this on scrunch: the following payload:
```json
{'function': 'cast', 'args': [{'variable': 'https://alpha.crunch.io/api/datasets/71f9ff66a4ad4e9385bbc4172f681d5f/variables/000002/'}, {'value': {'class': 'categorical', 'categories': [{'id': 1, 'name': 'one', 'missing': False}, {'id': 2, 'name': 'two', 'missing': False}, {'id': -1, 'name': 'No Data', 'missing': True}]}}]}
```
generated the following error:
`pycrunch.lemonpy.ClientError: (<Response [409]>, 'https://alpha.crunch.io/api/datasets/71f9ff66a4ad4e9385bbc4172f681d5f/variables/000002/cast/', {'status': '409 Conflict', 'message': 'Invalid casting type'`

@jjdelc: I can't find a way to make the cast work, what am I doing wrong ?

**Comment by jjdelc** [comment]
@mathiasbc when casting to categorical the API does not understand instructions of what value you want to be each category. 

Note that here you want to replace a derived variable with a new derivation that has a function `cast` on top of what you already had. This is different from http://docs.crunch.io/#convert-type which is for non-derived variables.

If you have a variable with derivation expression: 

```
{
function: +,
args: [
  {variable: http://...../abc/},
  {value: 3}
]}
```

And you want to cast that as categorical, then you need to wrap it with another function, PATCH the `derivation` attribute with an updated version:
```
function: cast,
args: [
  {
  function: +,
  args: [
    {variable: http://...../abc/},
    {value: 3}
  ]},
  {value: categorical}  
]
}
```

Note that the first argument, contains the original expression instead of `[variable: ...]`.

That will assume some categories, if you don't like those, then you have to do a `combine_categories` on top of that nesting, to remap the categories to whatever you want.

**Comment by xbito** [comment]
I don't think we want to cast derived categoricals to numericals. We shouldn't be thinking about that?

**Comment by mathiasbc** [comment]
@jjdelc: I'm not following exactly. Jamie wants to cast/convert/transform/derive a categorical to a numeric. Let's assume the categorical is not a derived variable, what is the correct way to do it ?

**Comment by jjdelc** [comment]
you want to replace the variable with the new type? Mutate it? Or create a new derived one that is the new type?

To mutate it, you need to follow the docs, POST to the /cast/ endpoint and will change the variable's type (and dataset schema, note that this will make streaming incompatible)

To create a new derived variable, then proceed as usual, POST to /dataset/id/variables/ where the derivation expression is as follows:
```
{
function: cast,
args: [
  {variable: http://..../catvarid/}
  {value: numeric}  
]
}
```

**Comment by xbito** [comment]
It is not a *new* variable. It is mutating it in place. And as far as Incan tell Mathias has been following the docs...

**Comment by xbito** [comment]
Jj take a look at https://github.com/Crunch-io/scrunch/issues/154#issuecomment-327735870

**Comment by mathiasbc** [comment]
ds = get_mutable_dataset(my_ds_id)
print(ds['Screening_Question'].type)
casted = ds.cast_new('variable_categorial', 'numeric')
print(casted.type)

**Comment by mathiasbc** [comment]
PR in place: https://github.com/Crunch-io/scrunch/pull/170
