### ISSUE TITLE
Filter for categorical using == doesn't work

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#156]
We must determine if this is a wide-spread scrunch problem or a problem in Crunch backend.

For one of the datasets creating this exclusion filter fails:

dataset.exclude(“ADcheckers == 1”)

with: 
{'status': 400, 'message': 'Failed to evaluate filter expression'})

Instead using dataset.exclude(“ADcheckers in [1]”) works.

ADcheckers is a categorical variable.The affected dataset is https://app.crunch.io/dataset/25686c973cef46128c8199c75342f478/browse/

**Comment by jamesrkg** [comment]
If this is a scrunch bug I wonder if it's the result of a quirk of implementation following [my comment](https://github.com/Crunch-io/scrunch/pull/121#issuecomment-303543898) about how operators should work for `multiple_response` variables.

In any case I would expect `"ADcheckers == 1"` and `"ADcheckers in [1]"` to be effectively equivalent against a `single` or `numeric`.

**Comment by jjdelc** [comment]
Can you confirm the final expression being sent to the server generated from `dataset.exclude(“ADcheckers == 1”)` ? 

It should be something like this:

```
{
  function: "==",
  args: [
    {variable: "ID for ADCheckers"},
    {value: 1}
  ]
}
```

**Comment by mathiasbc** [comment]
I confirm that Scrunch sends the expected payload:

```python
ds = get_dataset('61b36f4779a1483bba7c8addd5ace70c')
expr = parse_expr('ADcheckers == 1')
process_expr(expr, ds.resource))
```

```json
{
    "function": "==",
     "args": [
        {
  
  
  
  
  
  "variable":"https://alpha.crunch.io/api/datasets/61b36f4779a1483bba7c8addd5ace70c/variables/000000/"}, 
{
    "value": 1
}]}


{"function": "in", "args": [{"variable": "https://alpha.crunch.io/api/datasets/61b36f4779a1483bba7c8addd5ace70c/variables/000000/"}, {"value": [1]}]}
```

**Comment by mathiasbc** [comment]
@xbito, @jjdelc

**Comment by xbito** [comment]
@jjdelc any comments on this one?

**Comment by jjdelc** [comment]
I see two PRs associated to this ticket. None of them seems to point to this filter problem particularly.

It looks like this is a problem of the abstraction that the Crunch API exposes and the abstraction that Scrunch users want. In the API a Multiple response variable does not use the same operators as a normal categorical variable. So `==` won't work as expected on MRs.

If we wish so confuse both single categoricals and multiple response in scrunch, then scrunch should detect the type of the variable involved and use `in` function when the user typed `==`

**Comment by jamesrkg** [comment]
@jjdelc `in` is not equivalent to `==` .. (see [here](https://github.com/Crunch-io/scrunch/pull/121#issuecomment-303543898)).

@xbito unsure what's happened with this one or if it needs more attention?

**Comment by mathiasbc** [comment]
I think it's clear that for MR we use the syntax `var in []`
