### ISSUE TITLE
Manage dashboard view

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#157]
Provide API for creating/managing the new Crunch dashboard view. I'm unsure of its capabilities so we'll need to fill in what the exact requirements are from here. @jjdelc can you help in that?

**Comment by jjdelc** [comment]
The dashboard is just a dataset deck. In the API we just set the dataset.settings.dashboard_deck to be the deck URL we want.

If we have support for decks, then it's just matter of making the association between the two.

**Comment by mathiasbc** [comment]
we do have support for decks. 💯

**Comment by mathiasbc** [comment]
@jjdelc: I assume this is the documentation part of it ? http://docs.crunch.io/#fragments

**Comment by jjdelc** [comment]
@mathiasbc yes, the bit that says 

```
dashboard_deck | When set, points to a deck that will become publicly visible and be used as dashboard by the web client
```

**Comment by mathiasbc** [comment]
Taken care of in #153
