### ISSUE TITLE
Are we going to access dataset.owner and dataset.editor?

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#16]
We have a helper method Dataset.change_editor and the editor parameter in get_dataset, and for owner we have a preserve_owner parameter in Dataset.fork.

Should we expose an editor and an owner attribute. An editor can only be a user? An owner can be a User or a Project.

Should we have a getter and setter for both so it can be accessed like an attribute and be automatically written to the crunch_api? or shall we just expose get_owner/set_owner and get_editor/set_editor methods instead?

Setting owner is the only way to move a dataset to a Project if I'm not mistaken.

**Comment by dmonroy** [comment]
If I can vote I'd prefer to have the `editor` and `owner` properties with getter and setter, so we can do things like:

```python
>>> ds = get_dataset('My Dataset')
>>> ds.editor
https://app.crunch.io/api/users/123456
>>> ds.editor = me
>>> ds.editor
https://app.crunch.io/api/users/987654
```

**Comment by nealrichardson** [comment]
Can you have a nicer print method for that getter and setter so that your users aren't seeing URLs?

**Comment by dmonroy** [comment]
That would be better!

**Comment by dmonroy** [comment]
thinking again, it might require us to create a class for users and other for projects (#14) so we can implement the repr and str methods and still be able to use in api requests. I may be wrong, btw.

**Comment by xbito** [comment]
This has been implemented already as part of the Project and permission management.
