### ISSUE TITLE
[OrderAPI] `before` and `after` should be aware of `Variable` and `Dataset` instances

### ISSUE THREAD

**Issue by skriems** [Crunch-io/scrunch#162]
when using the `before` and `after` keyword arguments in the `order.place` method it is needed to provide the dataset id, instead of just the dataset object. This could be user friendlier and more intuitive

now:
```python
project.order.place(ds1, '|A Group', before=ds2.id)
```
suggested:
```python
project.order.place(ds1, '|A Group', before=ds2)
```

**Comment by xbito** [comment]
An id or dataset object should be acceptable

**Comment by jamesrkg** [comment]
Order API has been deprecated.
