### ISSUE TITLE
Enable control for geodata mapping

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#164]
References:

https://app.crunch.io/api/geodata/2b64724ce81c41c9bdc2436fb0bf6026/
https://app.crunch.io/api/geodata/2b64724ce81c41c9bdc2436fb0bf6026/
http://docs.crunch.io/#geodata-for-common-applications

**Comment by dmonroy** [comment]
@jamesrkg please let me know if the work I made on #184 and described in the [Geodata](../wiki/Geodata) wiki page meets your needs.

**Comment by jamesrkg** [comment]
@dmonroy forgot to comment last month: docs are great, and this all works as expected. The gap now is the availability of geodata for the variables we use, but that's not your problem!
