### ISSUE TITLE
Set values as missing for numeric variable

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#165]
We need to be able to set a value as missing on a numeric variable. The API documentation is not clear on this. Under the PATCH section for variables it says that altering missing rules "are best or only achieved elsewhere", but it doesn't say where.

**Comment by xbito** [comment]
Seems like we have done that manually in the past. It should be possible to add something to scrunch to tackle this.

**Comment by jjdelc** [comment]
We have a `/missing_rules/` endpoint under each variable, a PUT request to add/edit/delete missing rules.
http://docs.crunch.io/#missing-values

**Comment by mathiasbc** [comment]
`variable.set_missing_rules` allows this already.
