### ISSUE TITLE
Recover the project parameter for get_dataset and add it to the replacements

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#172]
Here you can see that get_dataset used to have a project parameter. We must bring that back into the compatibility layer and include it in the get_dataset replacements.

https://github.com/Crunch-io/scrunch/commit/f23c6019153c36664add23ae0016829afa163c10#diff-10a14081413b0535e4d0097c2ad71a58L108

**Comment by mathiasbc** [comment]
@xbito: We no longer need to specify a project because get_dataset_* will search on every project.

**Comment by mathiasbc** [comment]
Well I see it only does so when passed an ID, I will check and see it restored if needed: https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L130

**Comment by xbito** [comment]
Searching on every project can end up getting expensive for some users. So if we can specify the project we could be saving the planet from climate change.

**Comment by mathiasbc** [comment]
Great then, I'm up for climate protection so I will add it back.

**Comment by mathiasbc** [comment]
done: https://github.com/Crunch-io/scrunch/commit/18e82da449e50875e94183ee5cb3ed5a65b915f9
