### ISSUE TITLE
Simplify API for handling missing_rules

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#173]
Working with missing_rules feels a bit too raw as we're getting/setting actual payloads. Since the payloads are so basic, can we simplify them and add some conveniences? If a missing rules class handled these, methods could be used to work with them in a similar way to filters.

```python
>>> ds['open_realrange'].missing_rules
{u'not asked': 999, u'skipped': 998}

>>> ds['open_realrange'].missing_rules.keys()
[u'not asked', u'skipped']

>>> ds['open_realrange'].missing_rules[u'not asked']
999

>>> ds['open_realrange'].missing_rules[u'not asked'] = -1
>>> ds['open_realrange'].missing_rules
{u'not asked': -1, u'skipped': 998}

>>> ds['open_realrange'].missing_rules[u'skipped'].remove()
>>> ds['open_realrange'].missing_rules
{u'not asked': -1}

>>> ds['open_realrange'].set_missing_rules({u'not asked': 999, u'skipped': 998})
>>> ds['open_realrange'].missing_rules
{u'not asked': 999, u'skipped': 998}

>>> ds['open_realrange'].missing_rules.add({u'no data': -1})
>>> ds['open_realrange'].missing_rules
{u'not asked': 999, u'skipped': 998, u'no data': -1}
```

**Comment by mathiasbc** [comment]
@jamesrkg: Seems like a good idea, could you be more specific about the methods you would like `missing_rules` to support ?

**Comment by xbito** [comment]
Scrunch has too many dict-like objects that don't behave completely as a dict. We should either do a dict here completely (and preserve set_missing_rules for compatibility) or do nothing at all.

**Comment by jamesrkg** [comment]
Sounds like a good approach to me. 👍

**Comment by mathiasbc** [comment]
PR: https://github.com/Crunch-io/scrunch/pull/175
