### ISSUE TITLE
ds.fork() should always return a MutableDataset

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#176]
Currently:

```python
>>> print type(ds)
>>> fk = ds.fork()
>>> print type(fk)

<class 'scrunch.mutable_dataset.MutableDataset'>
<class 'scrunch.datasets.BaseDataset'>
```

Since a `BaseDataset` doesn't carry all the same methods as a `MutableDataset`, I can't do everything I want to it, such as `fk.delete()` which throws `AttributeError: 'BaseDataset' object has no attribute 'delete'`.

Presumably, even if `ds` was a `StreamingDataset`, forks should be of type `MutableDataset` since forks are not connected for streaming.

**Comment by xbito** [comment]
@jjdelc are forks going to inherit the streaming properties from the parent and have the same protections?

**Comment by jjdelc** [comment]
This is something we've discussed implementing the feature. The attribute is set by the backend by default.

The problem with returning a mutable dataset on fork is that it allows you to change your fork in a non mergeable state, which is a workflow that YG uses a lot. If you want to indeed break compatibility between your fork and the parent it should be a deliberate operation. 

What scrunch can do is implement a method on a `BaseDataset.make_mutable` and return a new instance (referring to the same dataset in the API) that now allows to do breaking operations.

**Comment by mathiasbc** [comment]
`fork()` now returns an instance of MutableDataset or StreamingDataset depending on the type of dataset the fork is from. https://github.com/Crunch-io/scrunch/commit/1c8ebc51cff1c7a732da2db27a3b2e724a08e5f1

Hopefully that helps you @jamesrkg

**Comment by jamesrkg** [comment]
Thanks @xbito @jjdelc @mathiasbc - this works. I'll add a new ticket for `BaseDataset.make_mutable`.
