### ISSUE TITLE
Group.remove()

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#183]
We need a way to remove/delete a Group, either in a project or variable hierarchy.

**Comment by mathiasbc** [comment]
Seems a little bit complicated deleting a group. I want to include @skriems to see if he has a suggestion. Also @jjdelc.
http://docs.crunch.io/#dataset-order

**Comment by jamesrkg** [comment]
What about grabbing the entire order, removing it from the Python obj, then re-POST-ing the whole thing?

**Comment by skriems** [comment]
@jamesrkg , @mathiasbc: while working on the order API I also missed a way to remove Groups. I'm not 100% up to date with scrunch, but I guess the question would be: What does the user want to achieve? As for the `DatasetVariablesOrder` I don't think the intention would be to delete those variables completely from the dataset (at least not if it's a `StreamingDataset`). Possibly yes for `MutableDatasets` though...
When deleting a Group in the `ProjectDatasetsOrder`, should those Datasets be removed from that Project? Then we would have to assing a new owner, probably the maintainer? Or should everything inside that Group shifted into the root Path? (see `place` method)?

I'm not sure if Crunch supports deleting those Groups entirely - iirc they weren't shown in the UI if empty.

**Comment by mathiasbc** [comment]
I started working on this but I didn't find an obvious thing to do with the Variables in a Group that gets removed. @jamesrkg what are your intentions by removing a Group ?

**Comment by xbito** [comment]
I don't think that the effects of removing a group is going to be clear, different persons might expect different results, I can imagine multiple of them:
Variables and subgroups go to the parent of the group to be deleted.
Variables and subgroups go to the root
Variables and subgroups are hidden
* All of the above but also subgroups are dissolved too.

In this case I vouch for explicitness, group removal should happen by reorganizing all its members clearly establishing where the variables/subgroups should end up.

**Comment by jamesrkg** [comment]
This originally came up because someone accidentally added a group to a Project and then couldn't get rid of it. Empty groups in a project hierarchy are not hidden by default (as an empty variable group would be). Even if they were hidden, it seems unhelpful to require users to live with every group they ever created (and then decided they don't need) even if they are hidden. If the user knows its junk they should be able to trash it.

However, I can see there are more use cases hidden in here than I'd originally considered, though.

What if `.remove()` only worked on an empty group as an initial implementation? This would force users to manage its contents as needed, considering different users may expect/need different results as you say @xbito .

I'm not sure how frequently a mass-delete-via-group-delete would be needed, or even if such a thing is consistent with where Crunch conceptually draws a line between order and variables. Can we keep this simple and deal with those additional use cases as extensions of this method as/when/if they arise (via kwargs).

**Comment by xbito** [comment]
Ok, deleting a group only if it is empty could work, but is there API support for that @jjdelc ? What do you say? Is it just a matter of posting the whole ordering object without mentioning the group?

**Comment by mathiasbc** [comment]
There isn't a way to directly delete a Group through the API, we would need to rePOST the modified object with the missing group name.

**Comment by mathiasbc** [comment]
I added a PR for review: https://github.com/Crunch-io/scrunch/pull/185

**Comment by mathiasbc** [comment]
and merged
