### ISSUE TITLE
BaseDataset needs add_user method

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#186]
Currently receiving:

`AttributeError: 'MutableDataset' object has no attribute 'add_user'`

**Comment by jamesrkg** [comment]
@mathiasbc an we also please have the ability to get Crunch to send a notification email to new users of a dataset (or not) as per the UI.

**Comment by mathiasbc** [comment]
This is the default behaviour when adding users to a dataset through the API as well. Implemented now: https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L780

**Comment by jamesrkg** [comment]
Thanks for this @mathiasbc . 👍
