### ISSUE TITLE
Need to be able to add a single categorical_array subvariable to a multitable

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#188]
This is possible from the UI and also rcrunch.

We need some syntax to be able to add a single `categorical_array` `subvariable` to a multitable.

Something like:

```python
mtab = ds.create_multitable(
    name='tester-table',
    template=[
        'catarray[subvar_1]',
    ],
    is_public=False
)
```

**Comment by mathiasbc** [comment]
I added some code to deal directly with variables, I made it work with subavariables like:

```python
mtab = ds.create_multitable(
    name='tester-table',
    template=[
        'ds[catarray][subvar_1]',
    ],
    is_public=False
)
```

But I don't know if the desired result is what you are after, so I would appreciate a review and test here @jamesrkg

**Comment by jamesrkg** [comment]
@mathiasbc I've tried this. It doesn't throw an error but the multitable appears to be broken, somehow, since it's blank/doesn't populate anything.

I'd also prefer a syntax different to `'ds[catarray][subvar_1]'`, because a reference to `ds` it out of place inside the string. The user may not have even called their instance `ds`. Besides `ds` should be implied from `ds.create_multitable(...)`. Can we go with `'catarray[subvar_1]'` instead, if you want to keep the square brackets?

**Comment by jamesrkg** [comment]
Forgot to mention, you can see the desired result by creating this from the app. I've created two multitables for you to reference on `4f2ebd029ff2414191537eff6037099f`, see `single_subvariable` and `full_categorical_array` (which is simply all of the single subvariables next to each other).

**Comment by mathiasbc** [comment]
@jamesrkg: Ah, sorry. The template is now meant to receive references to variables, not strings only. So my code above should have been:

```python
mtab = ds.create_multitable(
    name='tester-table',
    template=[
        ds['catarray']['subvar_1'],
    ],
    is_public=False
)
```
The reason you were getting an empty MT is because scrunch was trying to find a variable named `ds['catarray']['subvar_1']` and of course it was not founding it and thus creating an empty MT. Can you pls try again ?

**Comment by jamesrkg** [comment]
@jjdelc shouldn't the API return an error if we're asking Crunch to set up a multitable with a variable that doesn't exist? Would like a catch there but not sure it should be up to scrunch to catch it.

**Comment by mathiasbc** [comment]
It's technically not a variable name, Scrunch allows expressions in the template, so we need to convert the expression to a JSON. It's thus difficult to know it it's a variable name, or an expression or a variable that doesn't exist or an expression.

**Comment by jamesrkg** [comment]
@mathiasbc ok this does work, thanks for explaining. To labor the point a bit more though, it would be good if we _could_ write `'catarray[subvar_1]'` in addition to `ds['catarray']['subvar_1']` for consistency, since all non-subvariable items in the template can be given as strings. It would be a bit messy to have to write:

```python
mtab = ds.create_multitable(
    name='tester-table',
    template=[
        'q1',
        'q2',
        'q3',
        ds['q4']['q4_1'],
        ds['q4']['q4_6'],
        'q5',
        'q6'
    ],
    is_public=False
)
```

I'd prefer:

```python
mtab = ds.create_multitable(
    name='tester-table',
    template=[
        'q1',
        'q2',
        'q3',
        'q4[q4_1]',
        'q4[q4_6]',
        'q5',
        'q6'
    ],
    is_public=False
)
```

This will be more in-line the using simply `'q4'` for the entire array, as opposed to suddenly having to switch to `ds['q4']`.

**Comment by mathiasbc** [comment]
I see the point to that. I will see if I can work something to make it work like that.

**Comment by jamesrkg** [comment]
Regarding expressions in the template preventing scrunch from detecting a variable reference that doesn't exist, doesn't that mean that the error is eventually Crunch's to identify? At some point Crunch must know it's being asked about a variable that doesn't exist.

**Comment by mathiasbc** [comment]
@jamesrkg: Yes but our expression parser is very complex and has to deal with many cases, it also is dataset or variable agnostic, so it doesn't know if something is a variable, an operator or anything else. Because of this exactly, When referring to variables or subvariables in a template we need the syntax as I described above.

```python
mtab = ds.create_multitable(
    name='tester-table',
    template=[
        ds['q1'],
        ds['q4']['q4_1'],
        ds['q4']['q4_6'],
        'q1 > q2' 
    ],
    is_public=False
)
```

**Comment by jamesrkg** [comment]
@mathiasbc ok, understood, and not the end of the world. Am I right to think when adding a full categorical_array, however, we could still use `'q4''` rather than switching to the `ds['q4']` style? If so, then it's easy enough to remember when adding a single subvariable, the direct-variable approach is needed.

I think this is what you said but there was a typo in your reply here: "I recommend doing this when referencing _sub_-variables directly ...". Is that right?

**Comment by mathiasbc** [comment]
Yes, a variable can be declared as both `ds['var']` or `'var'` and subvariables only with `ds['var']['subvar']`, but of course the recommendation would be to refer to every kind of variable with it's programatic reference `ds['']` to maintain a sort of standard.

**Comment by mathiasbc** [comment]
I will close the ticket as apparently we reached and agreement and the main point was added to the code.
