### ISSUE TITLE
Control default notes visibility

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#189]
Apparently it's already possible to control the default visibility for `notes` on a dataset (this is otherwise a setting for each user). @jjdelc can you advise on the payload for this and where to direct it?

**Comment by jjdelc** [comment]
The dataset entity has a `notes` attribute that is writeable only by dataset editors, but readable to all. I don't recall it having per user or visibility controls. Are we talking about the same field? 

Each user entity, has a `preferences` field that is a free form object that clients use to store per user preferences, the webapp uses to store some things and such. But the backend makes no distinction of this attribute's contents.

**Comment by jamesrkg** [comment]
@jjdelc I'm not talking about the the dataset `notes`, but rather the visibility of variable `notes` when viewing variable cards. I think this is the second thing you describe but you lost me a bit at the end there. Right now using the web app a user can show/hide variable `notes`, but it requires each user doing this themselves (I believe variable `notes` are hidden by default?). Doug said that the ability to change the default setting for variable `notes` for all users was something we should be able to control with an API command.. against a dataset? Unsure of details beyond that.

**Comment by jjdelc** [comment]
Ok, I see what you mean the variable notes.

This toggle is stored under the user preferences as a user setting (per user, not per user/dataset), meaning that if you hide variable notes, then other datasets will also hide notes. 

The default value is the absence of those attributes set in the user's endpoint (/user/ endpoint, attribute `preferences`). Which defaults to False. This means that right now you can't make it to be default True for new users that get access to the dataset on the UI.

**Comment by jamesrkg** [comment]
Right, I'm closing this then because it sounds like it's not actionable.
