### ISSUE TITLE
After integrating a variable, need to get the dataset again before editing it

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#194]
If i `integrate` a derived variable, I need to use `get_dataset` again before I can edit the now-integrated variable. `ds.resource.refresh` isn't enough to make it work, but regardless, can this be something that is handled inside `integrate`?

**Comment by jamesrkg** [comment]
Does it need `self._reload_variables()`?

**Comment by mathiasbc** [comment]
Yes, what we need is self.dataset._reload_variables(), to make the Variable have it's dataset refresh the reference to it's variables. I added this and The following behaviour occurs:

```python
print(ds['test4'].derived)  # --> True
ds['test4'].integrate()
print(ds['test4'].derived)  # --> False
```
