### ISSUE TITLE
(non-derived) Edit material/integrated variable in-place

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#197]
We need a way to make ad hoc edits to a material/integrated variable using filter expressions to isolate a subset of rows. This is a common operation in pandas/R, for example:

```python
# pandas example
df.loc[df['age'] > 18, 'seg'] = 3

# possible scrunch example
ds['seg'].filter('age > 18') = 3
```

In the above scrunch example the string given to filter would be any supported filter expression.

**Comment by mathiasbc** [comment]
@jamesrkg: If my understanding is correct you are trying to set the value of a subset of subvariables  to 3 ? If not, what implies `filter()` on a variable ?

**Comment by mathiasbc** [comment]
@xbito, @jjdelc: As Fernando said, we need first an API to manage values first and then this approach would be one way to interact with Dataset values. I know Fernando wanted JJ to give his opinion and how could scrunch handle value interactions.

**Comment by jjdelc** [comment]
There is support in the dataset's `/table/` endpoint to update variables' values:

Here's an example using pycrunch:
```
ds.table.post({
            "command": "update",
            "variables": {
                text_var.body.id: z.value(None)
            },
            "filter": z.eq(text_var.body.id, "b")
        })
```

What you need to send is a payload with this shape:
```
{
  "command": "update",
  "variable": {
      "VARIABLEID": {'value': "new value"}
  },
  "filter": { ... filter .... }
}
```

**Comment by jjdelc** [comment]
We should make this a command on the dataset, "Replace values".

Note that the API will allow to update many variables at once (but all with the same filter). We could do something like:

`ds.replace_values({varid: val, varid: val}, filter='....')`

That way we map the input better to what the API supports.

**Comment by mathiasbc** [comment]
@jjdelc: I think it's a good approach, I can't find the section in the docs that specifies this though. What happens if we are updating more than one variable; should the key be named `variable` or `variables` ? and the content

**Comment by mathiasbc** [comment]
I think I got it now: https://github.com/Crunch-io/scrunch/commit/d319ba398a32bbb85d529cf6feb5f4e913a1a44c

@jamesrkg: Let me know what you think of it.

**Comment by jamesrkg** [comment]
@mathiasbc this looks good for `categorical`, `numeric` and `text` but we can't work out how to edit values for `categorical_array` and `multiple_response` subvariables. Neither referencing by subvariable name (`'q19_1'`) nor object(`ds['q19']['q19_1']`) seems to work. Is there something else we should try?

**Comment by mathiasbc** [comment]
@jjdelc: How should we deal with caterogical_arrays and MR ? I tried a couple of things but none seem to work.

**Comment by jjdelc** [comment]
@mathiasbc what have you tried sending as payload?

For arrays try sending `{column: [1,2,1,2]}` where the column has to have the full row of values for the array (same as number of subvars).

**Comment by mathiasbc** [comment]
@jjdelc, @jamesrkg: I changed the code to send a `column` value instead of a `value` when trying to replace a MR variable. The payload generated is:

```python
{
    "command": "update",
    "variables": {
        "8b0e4d61853c4a1f92748b7125883d0b": {
            "column": [
                0,
                1
            ]
        }
    }
}
```

Which fails with: `pycrunch.lemonpy.ClientError: (<Response [400]>, 'https://alpha.crunch.io/api/datasets/aaf07eaf6d094ca5ae6029d14c3b1621/table/', {'status': '400 Bad Request', 'message': "Error executing command: [Errno 2] No such file or directory: u'/var/lib/crunch.io/zz9repo/aa/aaf07eaf6d094ca5ae6029d14c3b1621/versions/master__000039/format.zz9.lz4'"})`

**Comment by jjdelc** [comment]
Is this happening to any dataset? This looks like an error of a dataset being corrupted. Unless this action is causing datasets to corrupt, then it's a bug we need to fix on the API.

**Comment by mathiasbc** [comment]
@jjdelc: yes this is happening in at least 4 datasets.

**Comment by jjdelc** [comment]
Do you have the IDs of those datasets? Are they pre-existing datasest? or are you creating new datasets for your tests?

What is the type of the variable you are trying to update?

**Comment by mathiasbc** [comment]
@jjdelc:
I deleted some, but:
aaf07eaf6d094ca5ae6029d14c3b1621
aafc79447fef4f98a9b0cb64a441e842

on Alpha

**Comment by mathiasbc** [comment]
This can be done now with https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L1654

**Comment by jamesrkg** [comment]
@mathiasbc Is usage for `multiple_response` and `categorical_array`  a list of row values as per `ds.create_variable(...)` for these variable types?

https://github.com/Crunch-io/scrunch/wiki/User-Reference#create_variable
