### ISSUE TITLE
Derive numeric variable failing

### ISSUE THREAD

**Issue by mathiasbc** [Crunch-io/scrunch#198]
When trying to create a new derived numeric variable with an arithmetic expression, Crunch returns: `pycrunch.lemonpy.ClientError: (<Response [400]>, 'https://alpha.crunch.io/api/datasets/aaf07eaf6d094ca5ae6029d14c3b1621/variables/', {'status': '400 Bad Request', 'message': 'There was a problem with your derivation expression'})`

```python
new_var = ds.create_numeric(
	alias='derived_test',
	name='Devired Test',
	derivation='(HHGR * 52) / 12'
)
```
The method `create_numeric` POSTS the following payload to the `/variables` endpoint:

```json
{
    "element": "shoji:entity",
    "body": {
        "alias": "derived_test",
         "name": "Test",
         "derivation": {
            "function": "/",
            "args": [
                {"function": "*", "args": [
                    {"variable": "HHGR"}, 
                    {"value": 52}]
                },
                {"value": 12}]},
    "description": "",
    "notes": ""
}}
```

The docs (http://docs.crunch.io/#other-transformations) point to these syntax although I can't infer if it allows nested complex expressions and variable-value operations or simply variable-variable operations.

**Comment by mathiasbc** [comment]
Apparently we need to referece variables by it's url now. I don't know when this change was made of it not, why we had these method send only variable as aliases and not full Crunch urls.

**Comment by malecki** [comment]
you’re correct, should be variable url.

**Comment by mathiasbc** [comment]
Fixed now in: https://github.com/Crunch-io/scrunch/commit/f855492c519540b8f6186d56fcaa0dd4ce02b5a4
