### ISSUE TITLE
(non-derived) Bind variables to form a multiple_response

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#205]
This can be done using rcrunch.

Probably related to #182.

**Comment by mathiasbc** [comment]
@jamesrkg: How is this different from creating a new MR variable `Mutabledataset.create_variable()` and then moving desired variables as subvariables with `Mutabledataset.move_as_subvariable()` ?

**Comment by xbito** [comment]
@mathiasbc I think that was Jamie would like is something similar to what was done for categorical_arrays here: https://github.com/Crunch-io/scrunch/blob/f86b08e2c46a461d76337d059e09cb47d4a9f14c/scrunch/datasets.py#L917

**Comment by jamesrkg** [comment]
@mathiasbc the docstring for `move_as_subvariable` says "Moves a variable as a subvariable of an existing array type variable", however the main use case here is that the multiple_response doesn't exist yet. In 99% of cases we'll be needing to create a new `multiple_response`.

**Comment by mathiasbc** [comment]
@jamesrkg: Mutabledataset now has a method `move_to_multiple_response` which will take care of this.
