### ISSUE TITLE
(non-derived) Re-order subvariables in an array

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#206]
This should be possible for both `multiple_response` and `categorical_array`. In the background it will most likely rely on being able to unbind (#204) and then re-bind (#205 #182) the subvariables, but a convenience wrapper around that once those are in place would be very handy.

**Comment by mathiasbc** [comment]
Not a very good idea, upon unbinding subvariables from some variables the variable will get delete. I will have to see if the API offers a way to re-order subvariables in place.
