### ISSUE TITLE
create_variable(var_type='multiple_response', ...) categories should be optional

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#209]
When trying the following:

```python
new_var = ds.create_variable(
    var_type='multiple_response',
    alias='football_clubs',
    name='Football clubs',
    description='Which football club do you follow?',
    categories=[
        {'name': 'Not selected', 'id': 2, 'numeric_value': 2, 'missing': False},
        {'name': 'Selected', 'id': 1, 'numeric_value': 1, 'missing': False}
    ],
    subvariables=[
        {'name': 'Subvariable 1', 'alias': 'subvar1', 'id': 1},
        {'name': 'Subvariable 2', 'alias': 'subvar2', 'id': 2}
    ]
)
```

If I leave out `categories` in the above I get this error:

`ClientError: (<Response [400]>, 'https://app.crunch.io/api/datasets/4f2ebd029ff2414191537eff6037099f/variables/', {u'status': u'400 Bad Request', u'message': u'Variables of type multiple_response require a `categories` attribute'})`

But `categories` should be optional in this case because a default categories list for `multiple_response` should be assumed if not given, namely the one I have included above. These seem to be the standard categories for `multiple_response` that I have seen in Crunch so far (ignoring skipped/not asked which I don't believe would be included in the generic case).

**Comment by mathiasbc** [comment]
@jamesrkg: Seems reasonable. I will have the method default categories to:

```python
[
        {'name': 'Not selected', 'id': 2, 'numeric_value': 2, 'missing': False},
        {'name': 'Selected', 'id': 1, 'numeric_value': 1, 'missing': False}
]
```
when the variable being created is of type MR and no categories are given.

**Comment by mathiasbc** [comment]
Implemented
