### ISSUE TITLE
(derived) Setting a filter expression to define the base of an array variable

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#215]
This is related to/clarifies #196. This ticket should put what is described in that ticket into context.

We need a way to use a filter expression to define the base for an array variable. All rows that do not satisfy the filter expression should be set to missing for the entire variable (so, all subvariables).

This is related to #196 because such a filter would be needed to establish what the base of the new variable described there is, by setting a filter such as that the original is not empty.

This is also related to #216 which requests for the same sort of control but at the subvariable-level, rather than the variable-level.

Example for clarity (not necessarily an API suggestion):

```python
ds[alias].base_filter = "valid(other_array)"
```

**Comment by xbito** [comment]
@jjdelc over here too, is that possible?

**Comment by jamesrkg** [comment]
This would actually be addressed by #228 so I'm going to close it.

At most this would be a convenience for overwriting any existing data with `-1` based on a given filter. If #228 was resolved I'm not sure it would be needed, or at least it would not be pressing as this is effectively a workaround for that problem.
