### ISSUE TITLE
(derived) Setting a filter expression to define the base of an array subvariable

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#216]
This is related to/clarifies #196 and #215.

We need a way to use a filter expression to define the base for an array subvariable. All rows that do not satisfy the filter expression should be set to missing *for that subvariable*.

This is related to #215 which requests for the same sort of control but at the variable-level, rather than the subvariable-level.

Example for clarity (not necessarily an API suggestion):

`ds[alias][subalias].base_filter = "valid(other_subvariable)"`

**Comment by xbito** [comment]
@jjdelc is that possible in the API?

**Comment by jamesrkg** [comment]
As with #215 this will actually be addressed by #228, so I'm closing it.
