### ISSUE TITLE
Variables created using ds.copy_variable() cannot be integrated

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#236]
This must be somehow related to #234.

```python
# works for variables created using create_categorical
>>> new_var = ds.create_categorical(...)
>>> print new_var.derived
True
>>> new_var.integrate()
>>> print new_var.derived
False

# doesn't work for variables created using copy_variable
>>> new_var = ds.copy_variable(...)
>>> print new_var.derived
True
>>> new_var.integrate()
>>> print new_var.derived
True
```

Here is the companion method in rcrunch, which you can see has a `deep=False` kwarg, which afaict controls whether or not the result is a derived (`deep=False`) or material (`deep=True`) copy of it:

https://github.com/Crunch-io/rcrunch/blob/4f35b923952ac1ad318cd432e6d9022b9c818e8f/R/copy.R#L26

This dimension of control doesn't exist in the scrunch version of the method.

**Comment by mathiasbc** [comment]
There is a logic behind this behaviour. https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L1026-L1035 If a variable is a derivation, one should expect that variable to be derived, and in scrunch a variable witha  derivation upon copy, it's just cloning the derivation into a new variable. But if Rcrunch allows to overwrite that behaviour I'm completely fine so I added the same thing.

`copy_variable(..., derived=False | True)` now allows this. Still if we want the default behaviour and let Crunch decide if our variable should be derived or not, we can pass `derived=None` or not pass it at all.
