### ISSUE TITLE
Is it correct to use numeric_value in expressions?

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#239]
Looking at the code it seems that when using names we transform them to numeric_value. Should we be doing that or should we be using the category id? There is a recent request to stop setting numeric values in categories by default. Maybe we were just taking advantage of the fact that for stream/uploads we automatically set numeric_value = category_id?

https://github.com/Crunch-io/scrunch/blob/85d0e7cef720cf36896b5420db44215ff28b1bdf/scrunch/expressions.py#L505

https://github.com/Crunch-io/scrunch/blob/85d0e7cef720cf36896b5420db44215ff28b1bdf/scrunch/expressions.py#L520

**Comment by jamesrkg** [comment]
Definitely not. For example it's entirely possible that a `numeric_value` could be something like `37.5` or `-1`. They may also change as analysis requirements change, so should not be assumed to be stable.
