### ISSUE TITLE
Headings/subtotals - list/remove/clear/rename/edit/etc.

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#241]
Some additional control that would be useful in relation to headings and subtotals:

* List existing headings or subtotals
* Remove a heading or subtotal
* Clear all headings or subtotals
* Edit an existing heading or subtotal

It looks from the UI that these must all be supported by the API somehow.

**Comment by mathiasbc** [comment]
1.- `var.transformations()`
2.- We can only remove all: `var.add_heading('clearing', categories=None)`
3.- The above case
4.- This might get complicated but it's perhaps doable.

**Comment by jamesrkg** [comment]
As these are mostly solved already we can abandon this one.
