### ISSUE TITLE
Re-running headings/subtotals produced unexpected results

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#242]
While testing `add_heading` and `add_subtotal` I attempted to re-run my code between dropping into the UI to remove the headings/subtotals I had created previously. This produced unexpected results.

At first, although I had successfully removed the old headings/subtotals with the UI. When I re-ran my code I ended up with duplicate headings/subtotals for all of them, as if it re-activated the ones that I had removed.

I tried to add `ds._reload_variables()` but this resulted in only the subtotals being created.

The more I tried the less expected it became until I could only get 1 or two of all the ones I had requested.

Some of the inital confusion is, I think, because the docstring is not correct in how it describes chaining these together:

```
        Note: to concatenate subtotals the procedure requires to reassign the variable:
        var = var.add_subtotal('This is subtotal', [1, 2], 'top')
        var = var.add_subtotal('At the bottom', [3], 'bottom')
```

Since returning each time to `var` appears to "reset" the headings/subtotals to blank. This means you only end up with the last heading/subtotal you attempted.

I've tried variations of the below code (returning or not returning the `var_changed`) and can't find a version that works as expected. If you do see it work as expected then please rinse/repeat a few times and I'm sure you'll start to see the bug evolve.

```python
var = ds['Qintend']
# headings
var_changed = var.add_heading('This is heading at the top', anchor='top')
var_changed.add_heading('This is heading at 1', anchor=1)
var_changed.add_heading('This is heading at 3', anchor=3)
var_changed.add_heading('This is a heading at the bottom', anchor='bottom')
# # subtotals
var_changed.add_subtotal('This is a [4, 5] subtotal with no anchor', categories=[4, 5])
var_changed.add_subtotal('This is a [4, 5] subtotal with at 1', categories=[4, 5], anchor=1)
```

**Comment by mathiasbc** [comment]
```
var = ds['Qintend']
# headings
var_changed = var.add_heading('This is heading at the top', anchor='top')
var_changed.add_heading('This is heading at 1', anchor=1)
var_changed.add_heading('This is heading at 3', anchor=3)
var_changed.add_heading('This is a heading at the bottom', anchor='bottom')
# # subtotals
var_changed.add_subtotal('This is a [4, 5] subtotal with no anchor', categories=[4, 5])
var_changed.add_subtotal('This is a [4, 5] subtotal with at 1', categories=[4, 5], anchor=1)
```

This example will only add the first 2 headings and probable the last one, because you are not refreshing the variable, as in, you need to grab a fresh variable instance everytime we add a heading or a subtotal.

To delete all `transformations (headings and subtotals)` simply do `var.add_heading('Ignore')`.

I tested this several times, I get the expected result.
