### ISSUE TITLE
Allow add_heading(..., categories=int)

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#245]
`var.add_heading` only makes sense tagging a single category but it requires a list of categories to be given. 

Instead of forcing `var.add_heading(..., categories=[1])` can we please also support the simpler `var.add_heading(..., categories=1)`?

I also can't help but wonder if this kwarg should be renamed to simply `category` for clarity, e.g. `var.add_heading(name="My heading", category=1, anchor="top")`.

**Comment by mathiasbc** [comment]
https://github.com/Crunch-io/scrunch/commit/3df6e0cf9c48aa353a29240c3eec432c87a1c2a4
