### ISSUE TITLE
pr.order.load() no longer registers a newly created group

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#249]
Previously, we could follow the these steps:

```python
pr = get_project(name_pr)
pr.order['|'].create_group(name=name_folder)
pr.order.load()
```

After which the newly created group would be visible in `pr.order`, however now that seems to not be the case.

**Comment by mathiasbc** [comment]
There is a misunderstanding here. the `order.load()` method is not intended to be called by users. I have changed that and make it private with the python convention or prepending an underscore `_load`. 

`create_group` or any other method that mutates a Project or Group takes care automatically of reloading it's resource and the way this should be used is:

```python
```
pr = get_project('Test Bench')
print(pr.order)
pr.order['|'].create_group(name='Group A')
print(pr.order)
pr.order['|'].create_group(name='Group B')
print(pr.order)
```
>>>> []


>>>> [
    {
        "Group A": []
    }
]


>>>> [
    {
        "Group A": []
    },
    {
        "Group B": []
    }
]
```
