### ISSUE TITLE
Windows encoding problems

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#251]
We're using a Window's machine with Jupyter Notebooks and the following methods:

`ds.order['|'].create_group()`
`ds.order['|Variables'].rename()`

Throw encoding errors for these characters (at least):

```
Unrecognized character: `
Unrecognized character: ~
Unrecognized character: !
Unrecognized character: @
Unrecognized character: #
Unrecognized character: $
Unrecognized character: %
Unrecognized character: ^
Unrecognized character: *
Unrecognized character: =
Unrecognized character: +
Unrecognized character: ;
Unrecognized character: :
Unrecognized character: "
Unrecognized character: '
Unrecognized character: |
Unrecognized character: <
Unrecognized character: .
Unrecognized character: >
Unrecognized character: ?
```

When fixing those, please verify that the following are also stable in this environment:

`ds.order['|Group {}'.format(use_unrecog_char)].insert()`
`ds.order['|'].append()`
`ds.order['|'].insert(before/after=)`
`ds.order['|Some group'].move()`

**Comment by mathiasbc** [comment]
I believe this is specific to the windows environment locale as I cannot reproduce it on *nix.

**Comment by jamesrkg** [comment]
@mathiasbc @xbito can we try again to resolve this one? We're getting to the point now where work-arounds (using R) are not viable because they interrupt an automated process (using python).

**Comment by alextanski** [comment]
To add to this:

I am able to create a project that contains e.g. a dot (``'.'``), see the folder ``'This folder name has a dot .'`` in the **SSC Review** project.

However, I cannot access this folder once created, for example:

```
pr = scrunch.get_project('SSC Review')
foldername = 'This folder name has a dot .'
pr = pr[foldername]
```

... throws:

`InvalidPathError: Invalid path This folder name has a dot .: it contains invalid characters.`
