### ISSUE TITLE
 create_categorical from datetime using rollup

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#253]
rcrunch offers the following:

```r
ds$new_var <- rollup(ds$date, "Y")
```

Which produces the following expression:

```json
{
  "function": "rollup",
  "args": [
    {
      "variable": "https://app.crunch.io/api/datasets/ab69c24715a04939811b5935d9b94ab4/variables/000000/"
    },
    {
      "value": "Y"
    }
  ]
} 
```

Which rolls the source `datetime` variable by year (`"Y"`) into a new derived categorical variable.

As with any other derived variable creation, this is what you'd include as the "derivation" member of the "body" of the variable entity payload.

**Comment by mathiasbc** [comment]
@jamesrkg: Could you provide and example of how would you use this in `scrunch` ? 

Is this only for `create_categorical` with argument `multiple=True` if I follow correctly ?

**Comment by xbito** [comment]
@mathiasbc I think the syntax should probably be something like:
dataset.rollup('new_var_alias', 'old_date_var_alias', <mask>)

We would need to know which masks are allowed, @jamesrkg can you help us with that? So far we know from your example that "Y" is allowed, meaning "year". I don't see mention to the possible parameters of rollup in crunch docs http://docs.crunch.io/object-reference/object-reference.html?highlight=rollup#date-functions @jjdelc @malecki  maybe you can add that to the docs?

**Comment by jamesrkg** [comment]
I found the following referenced in rcrunch:

https://github.com/Crunch-io/rcrunch/blob/1b8ab2f22f3b08d246cd50232c3322de963f0165/tests/testthat/test-expressions.R#L235

**Comment by jjdelc** [comment]
Yup that list is correct. The values are what Numpy accepts as time resolutions.
https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.datetime.html#datetime-units

The extra `Q` was added but it's a shortcut for `3M`.

**Comment by jamesrkg** [comment]
@mathiasbc the only one of these that comes out the same as if I do the rollup from the UI is `Day`. Can you take another look and compare the results against what you get when using the UI?

**Comment by mathiasbc** [comment]
I can't find how to do it in the UI. the only way seems to do a rollup on the current variable, but not create a new variable by doing a rollup on an existing datetime var. Anyway @jjdelc: what could be wrong: https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L926 ?

**Comment by jamesrkg** [comment]
It looks like the `rollup_resolution` in the created varaible needs to be addressed. Here is the variable body for one I created using `Y`:

```
  "body": {
    "name": "endtime (year)",
    "format": {
      "data": "%Y-%m-%d",
      "summary": "%Y-%m-%d"
    },
    "resolution": "Y",                   <------------
    "notes": "",
    "derived": true,
    "missing_reasons": {
      "No Data": -1
    },
    "private": false,
    "discarded": false,
    "alias": "endtime_Y",
    "rollup_resolution": "m",            <------------
    "derivation": {
      "function": "rollup",
      "args": [
        {
          "variable": "../000020/"
        },
        {
          "value": "Y"
        }
      ],
      "references": {
        "alias": "endtime_Y",
        "notes": "",
        "name": "endtime (year)",
        "description": ""
      }
    },
    "owner": null,
    "dataset_id": "d6d8ece2d18641b386275a19f9917856",
    "view": {
      "rollup_resolution": "m",         <------------
      "column_width": null
    },
    "type": "datetime",
    "id": "82fe73cd24654f0ab13e6d0a65c70aae",
    "categories": [],
    "description": ""
  },
```

**Comment by jamesrkg** [comment]
We're closing this and will replace with another ticket that better addresses the API in relation to `datetime` variables.
