### ISSUE TITLE
replace_values for array subvariables

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#256]
`replace_values` (https://github.com/Crunch-io/scrunch/wiki/User-Reference#replace_values) doesn't currently work for replacing the values of an array subvariable (`multiple_response` or `categorical_array`). 

```python
>>> for _, subvar in ds['test-uc1']:
...     print subvar.alias
test-uc1_1
test-uc1_2

>>> ds.replace_values({'test-uc1_1': 2}, filter='not QB in [1, 2]')
ValueError: <dataset_name> has no (sub)variable with a name or alias test-uc1_1
```

**Comment by jamesrkg** [comment]
For reference, here is how this is done using rcrunch:

```r
ds$A1[["None of these"]][ds$A1[["None of these (1)"]] == "selected"] <- "selected"
```

**Comment by mathiasbc** [comment]
The process seems alright. The generated payload that scrunch is sending to the API is:

```python
{  
    'command':'update',
    'variables':{  
        '001134.0001':{  
            'column':[  
                1,
                1,
                ...
            ]
        }
    },
    'filter':{  
        'function':'==',
        'args':[  
            {  
                'variable':'https://app.crunch.io/api/datasets/b8446edded684f03a4388326266b80ff/variables/000656/subvariables/0001/'
            },
            {  
                'value':1
            }
        ]
    }
}
```

**Comment by mathiasbc** [comment]
@jjdelc: any advice what could be wrong ?

**Comment by jjdelc** [comment]
You have to make sure you send the `column` list with the correct number of values, on this case you need to know that when filtering your table there will be only 23 matching rows, so you need to send only 23 values for those 23 rows.

**Comment by mathiasbc** [comment]
ah, well that looks like trouble. We would need to filter the Dataset first somehow. @xbito

**Comment by jamesrkg** [comment]
I'm not sure that's the problem, because that would be equally true of an expression that didn't reference a subvariable, e.g.:

```
ds['multiple']['multiple_2'].replace_values(value=1, filter='single_colorpicker == 2')
```

But this expression does work. It's only when the tested variable is a subvariable that nothing happens.

**Comment by jjdelc** [comment]
You mean to filter on particular subvariable value? You could construct your filter referring to `{variable: array_.subvariable_id}` and compare it to the category you want.

**Comment by mathiasbc** [comment]
@jjdelc So instead of:
```
    'filter':{  
        'function':'==',
        'args':[  
            {  
                'variable':'https://app.crunch.io/api/datasets/b8446edded684f03a4388326266b80ff/variables/000656/subvariables/0001/'
            },
            {  
                'value':1
            }
        ]
    }
```

do:

```
    'filter':{  
        'function':'==',
        'args':[  
            {  
                'variable': array_.subvariable_id
            },
            {  
                'value':1
            }
        ]
    }
```

and what exactly is `array_` ?

**Comment by jjdelc** [comment]
Either should work, the URL would get parsed to the dotted syntax, if you have the values you an just send the subvariable dot syntax. On that URL example `000656.0001`

**Comment by jamesrkg** [comment]
Can we extend the dotted form to the expression parser? This would be preferable both because it's explicit and would also more closely reflect the underlying API. I understand that, if possible, it might not fall into the scope of this ticket.

E.g.:

```python
ds['multiple']['multiple_1'].replace_values(value=1, filter='card_sort.card_sort_1 in [1]')
```

Currently this gives me:

```
ClientError: (
    <Response [400]>, 
    'https://app.crunch.io/api/datasets/73bb66513c764ab5b2f546202d21b1bb/table/', 
    {
        u'status': u'400 Bad Request', 
        u'message': u'Error executing command: Filter error: No expression class given.'
    }
)
```

**Comment by mathiasbc** [comment]
We are seeing this dotted syntax related to subvariables. I would prefer not changing the parser as it currently is, as @jjdelc mentioned "either should work". 

If we were to extend the dotted syntax to the parser, probably will be faster since we wouldn't be needing to build urls; does Crunch accepts variable ids for variables ? Or the dotted pattern is only allowed for subvariables ?

**Comment by jamesrkg** [comment]
@mathiasbc whatever you think is best at this time.

**Comment by jjdelc** [comment]
@mathiasbc  the dotted pattern is only for subvariables. The Id of the array variable and then the ID of the subvariable. That's the only case where it's used. 

The error `'Error executing command: Filter error: No expression class given.'` is because the ZCL sent was malformed, can you paste what it was?

**Comment by jamesrkg** [comment]
@jjdelc is this what you want to see?

```
{
  "filter": {
    "function": "==",
    "args": [
      {},
      {
        "value": 1
      }
    ]
  },
  "variables": {
    "000154.0001": {
      "value": 1
    }
  },
  "command": "update"
}
```

**Comment by jjdelc** [comment]
Yes, that's it. See the filter is malformed. The first arg is empty.

**Comment by xbito** [comment]
We are closing this one because we have a more general case about subvariables in expressions.
