### ISSUE TITLE
Editing numeric_value introduces encoding problem for category name

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#257]
This may or may not be specifically related to #251.

When editing the `numeric_value` of a category that has a name with non-ASCII characters, after the edit is completed, those non-ASCII characters are replaced with `?`.

**Comment by mathiasbc** [comment]
how exactly are you editing this attribute ? could you please post an example.

**Comment by jamesrkg** [comment]
Before edit:

![before-numeric_value-edit](https://user-images.githubusercontent.com/5341764/44489486-99dbf800-a629-11e8-9889-beec13e23444.png)

Then edit numeric value using:

```python
for i in [1, 2, 3, 4]:
    ds['single'].categories[i].edit(numeric_value=i)
```

![after-numeric_value-edit png](https://user-images.githubusercontent.com/5341764/44489512-ae1ff500-a629-11e8-876e-ef4ce770e10d.png)
