### ISSUE TITLE
ds.folders.root.children only returns Folder instances

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#259]
In the below, `item_url` is always in `index` and so `Folder` instances are returned for every item.

https://github.com/Crunch-io/scrunch/blob/f89f6541feaeb19e297978e3709df1cfe5ce1d0f/scrunch/folders.py#L129-L136

**Comment by jjdelc** [comment]
Thanks for the report, here's the PR to fix it https://github.com/Crunch-io/scrunch/pull/260/files 
I'll be merging and releasing this.
