### ISSUE TITLE
Figure out accessing categories

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#26]
We need to figure out still what we are going to do to access and edit categories. The docs currently say:

You can also access and edit categories for categorical variables. Either provide a complete list of new categories or if you want to change only the name of a category you can achieve that with:
[comment]: TODO are we going to access categories as var.categories instead? 
[comment]: TODO Will we have a Category class? What's the use case and design we are aiming for?

var.resource.body.categories[0]['name'] = 'My new category'
var.edit(categories=var.resource.body.categories)

We definitively want to avoid the ".resource.body." part. And how are we going to do the edit exactly? Are we aiming for:
ds.variable.categories[0].name = 'New name'

Or are we thinking about a categories object that can have helpers like the ordering one?
ds.variable.categories.append(**params)
ds.variable.categories.insert(**params)

There is also the complication that treatment between categories for normal variables and derived variables should be different?

We were chatting briefly about this with Jj and I'll leave it to him to document a proposal.

**Comment by jjdelc** [comment]
Added a section "Managing Categories" to the Google doc with examples of `edit_category` and `order_categories`.

Not sure if we need to handle add/remove categories. It is possible to do so easily on base categoricals but is not possible on derived categoricals or arrays so adding such support would be for a subset of categoricals only and would get confusing on when are things supported or not.

**Comment by jjdelc** [comment]
Updated the docs according to the comments. 
Work happening in https://github.com/Crunch-io/scrunch/tree/edit-categories

**Comment by xbito** [comment]
Done and merged.
