### ISSUE TITLE
Non-derived - delete category from a variable

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#262]
The use case for this one assumes that the user has already ensured there is no data referencing the category to be deleted.

This is possible with rcrunch with:
```r
[crunch] > categories(ds$var2)
[ 1 ]  male
[ 2 ]  female
[ NA ]  No Data
[ 3 ]  nope

[crunch] > categories(ds$var2) <- c(categories(ds$var2)[-c(3)])

[crunch] > categories(ds$var2)
[ 1 ]  male
[ 2 ]  female
[ NA ]  No Data
```

**Comment by xbito** [comment]
Assigning to me though it should really go to Anders.

Only Mutable Datasets should allow this.

**Comment by jamesrkg** [comment]
I put some details about an issue with the implementation in #270.
