### ISSUE TITLE
Non-derived - Variable.edit(alias=X)

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#264]
https://github.com/Crunch-io/scrunch/blob/dceb4da29706b9b60ef438ed87c8012ce9770149/scrunch/datasets.py#L2103-L2105

`alias` is in the `_IMMUTABLE_ATTRIBUTES` list but it should be in the `_MUTABLE_ATTRIBUTES ` list (though it would presumably need to be restricted to only non-derived variables).

**Comment by xbito** [comment]
Alias should be ok to mutate on non streaming datasets only.
We have to be careful with any caches the objects may have when renaming an alias.

**Comment by jamesrkg** [comment]
@mathiasbc we need a `ds._reload_variables()` so the locally instantiated dataset is aware of the change.
