### ISSUE TITLE
Non-derived - delete a subvariable

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#265]
This is possible with rcrunch with:

```r
> deleteSubvariable(ds$A1, 'None of these (1)')
> deleteSubvariables(ds$FFZL_q4_, c('FFZL_q4__ffzl_q4_1___FFZL_q4_grid', 'FFZL_q4__ffzl_q4_2___FFZL_q4_grid'))
```

**Comment by xbito** [comment]
Assigning to me though it should be Anders. 

This should only be possible with mutable dataset classes. I see the example provides the possibility of deleting a subvariable by name. We should only do it by alias. dataset.subvar_alias.delete() ?

**Comment by jamesrkg** [comment]
Yes, I think an implementation only by alias is enough for this ticket.

**Comment by anderstheet** [comment]
We have the ability to delete variables right now like this: ds['var1'].delete()
And we can delete subvariables like this: ds['grid1']['grid_item1'].delete()

Do you want another way to do it like this maybe? ds['grid1'].delete_subvariable('grid_item1')

**Comment by anderstheet** [comment]
We can delete variables like this: ds['var1'].delete()
And we can delete subvariables like this: ds['var1']['subvar1'].delete()

Do you want a helper function to the parent variable like this maybe? ds['var1'].delete_subvariable('subvar1')
