### ISSUE TITLE
Expression parser for variables including a space character

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#268]
Is there any way (with a justifiable amount of effort) the expression parser can support references to variables that include a space character, since this is supported in Crunch?

E.g.: `Final Completes == 1`

```
Unexpected error: <type 'exceptions.SyntaxError'>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\scrunch\datasets.py", line 1632, in export
    parse_expr(filter), self.resource)
  File "C:\ProgramData\Anaconda2\lib\site-packages\scrunch\expressions.py", line 421, in parse_
expr
    return _parse(ast.parse(expr, mode='eval'))
  File "C:\ProgramData\Anaconda2\lib\ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    Final Completes == 1
                  ^
SyntaxError: invalid syntax
```

The above example is from an export but it looks like the same error would occur no matter where the expression was used.

**Comment by xbito** [comment]
We are using python parsing mechanisms to parse the expressions. Trying to add support for multiple-worded variable names would be too big of a task for me to be comfortable with. It would demand a total re-structure of the parser.

**Comment by jamesrkg** [comment]
Fine by me, thanks @xbito .
