### ISSUE TITLE
Don't do get_dataset inside a Variable method

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#27]
A couple of methods in the Variable class do something like:
ds = get_dataset(self.resource.body.dataset_id)

The Variable object should have a reference to the dataset, it should be an __init__ parameter and it should be set when accessing the variable as ds['variable'].

Then we should remove those get_dataset calls from the methods in Variable.

**Comment by jjdelc** [comment]
The variable entity resource includes a "dataset_url" that points to its dataset which can be used to traverse up and fetch the dataset resource when needed. 

I doubt that we need any of the methods that our Dataset entity exposes to be used internally inside the Variable Entity, so we could probably do with just the shoji resource.
