### ISSUE TITLE
Deprecate BaseDataset.replace_values

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#281]
Now that we have (the better) `Variable.replace_values` we should deprecate `BaseDataset.replace_values`. 

A `DeprecationWarning` to start this off would be appreciated so that we can update scripts where required without encountering failures.

**Comment by mathiasbc** [comment]
This method needs to persist. At the Dataset level it allows to replace the values for many variables in one call, whereas at the Variable level it works, obviously, to the Variable instance reach.

The duplication is not an issue either given that `Variable.replace_values()` calls the `Dataset.replace_values()` method.
