### ISSUE TITLE
Fix updating of variable `view` attribute when changing `rollup_resolution`

### ISSUE THREAD

**Issue by jjdelc** [Crunch-io/scrunch#282]
The PR recently merged overwrites the variable's `view` erasing any other attribute that may have been set on it.

The right way to update an attribute in a variable's `view` is by reading the current value and only setting/updating the needed key and sending this updated value as the new value, otherwise you're replacing it with a brand new empty dict.

https://github.com/Crunch-io/scrunch/pull/279/files#diff-10a14081413b0535e4d0097c2ad71a58R2509

**Comment by mathiasbc** [comment]
https://github.com/Crunch-io/scrunch/pull/283
