### ISSUE TITLE
Error when appending datasets with no primary key set

### ISSUE THREAD

**Issue by ch33kygit** [Crunch-io/scrunch#289]
I have this dataset:  

[https://app.crunch.io/dataset/5ded0a5a2f1a4787ac8f78c48fe0e3df/browse](url)

where the data is correct APART from Q8 at wave 2 (the Don’t know is blank for wave 2, this is an DP error). So what I did was to create a fork from this dataset and removed the wave 2 data from it.

Then, I’ve fixed the wave 2 only dataset: 

[https://app.crunch.io/dataset/c8f55e3230b74433ad754f29e0579a52/browse](url)

and appended using delete_pk = False (below) onto the fork.

`
try:
    ds1.append_dataset(
    ds2, 
    autorollback=True, delete_pk =False
)
except pycrunch.shoji.TaskProgressTimeoutError as exc:
    exc.entity.wait_progress(exc.response)
    entity = exc.entity.refresh()
`
In which resulted in

> TaskProgressTimeoutError: Task Progress did not complete before 30 seconds timeout. Trap this exception and call exc.entity.wait_progress(exc.response) to wait for completion explicitly.

This has seemed to work, however, and this is the resulting dataset: 

[https://app.crunch.io/dataset/6190f6da870f47199d15332176786cc5/browse](url)

This has fixed wave 2 at Q8. However, this has messed up the data for other waves in derived grid variables such as Q9, Q11, Q13, and Q15 for other waves.

So comparing:
Pre append version: [https://app.crunch.io/dataset/5ded0a5a2f1a4787ac8f78c48fe0e3df/browse](url)
Post append version: [https://app.crunch.io/dataset/6190f6da870f47199d15332176786cc5/browse?variableId=c0f8cc7b3c8b44b888f960f50d8cbb15](url)

You can see, for example, that at Q11_BRAND_1_dp (“Content satisfaction - BBC News”) the figures differ between the two datasets (bar wave 2). From what I can see, it looks like the subvariables have reshuffled but the order of the labels remained the same. 

![pre-append](https://user-images.githubusercontent.com/32849964/45034556-c2171e00-b04f-11e8-9218-758802f36d05.jpg)
![post-append](https://user-images.githubusercontent.com/32849964/45034558-c3e0e180-b04f-11e8-9ca6-fcb22fc07963.jpg)

For example, 
"BBC News - National news (Q11)" figures differ between the two datasets but "BBC News - National news (Q11)" in pre-append version matches with "BBC News - Music (Q11)" in the post-append version.

**Comment by jonkeane** [comment]
I've been working with Jun on this issue, and there are a couple of different things that are going on here. I'm working on the array after append being inconsistent, so y'all can safely ignore that (it's not an scrunch-specific issue).

What I do see, however, is that it appears that scrunch errors if you try to append to a dataset that has no primary key set. Looking through the code it looks like https://github.com/Crunch-io/scrunch/blob/master/scrunch/mutable_dataset.py#L237-L240 gets called regardless if the dataset has a primary key or not. When it attempts to delete a primary key that doesn't exist, it errors and the append does not proceed. You probably want to check that the primary key exists before attempting to delete it (or alternatively catch the server response and continue on with the append)
