### ISSUE TITLE
get_project targeting nested project

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#296]
To get a nested project the following is necessary:

`pr = scrunch.get_project('US').get('|California|San Francisco')`

It would be convenient for `get_project` to manage the `get`:

`pr = scrunch.get_project('US|California|San Francisco')`

**Comment by anderstheet** [comment]
Made PR:
https://github.com/Crunch-io/scrunch/pull/329

**Comment by xbito** [comment]
Merged PR.
