### ISSUE TITLE
compare_dataset sometimes fails with too many values to unpack

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#297]
https://github.com/Crunch-io/scrunch/blob/6309e96622588099dc27a84c5e2585c38a95a0f4/scrunch/mutable_dataset.py#L213-L215

In this case `rules1` is a `dict` and so should be `rules1.iteritems():`.

**Comment by mathiasbc** [comment]
Should be fixed with: https://github.com/Crunch-io/scrunch/commit/e5d995d065ff675c346d7feedc481738cdb53c3f
