### ISSUE TITLE
Should get_dataset be aware of the archived status?

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#30]
The rcrunch library has a parameter for loadDataset that distinguishes between "active", "all", "archived" datasets.

Should our get_dataset be aware of that distinction too and avoid the datasets that are archived by default?

**Comment by jjdelc** [comment]
The situation is problematic when fetching by name returns many results. 

If requested by ID, we should return regardless of the archived status, but if requested by name, what is the current behavior when many datasets are available under the same name? (This is the scenario that I create a dataset myself and then I get shared another dataset that has the same name).

**Comment by xbito** [comment]
Currently we grab the first one, we don't care if the result list had more than one dataset.

**Comment by xbito** [comment]
I'm closing this issue. Really until we have users we can't really know if this is a flag we should be giving major importance or not.
