### ISSUE TITLE
Project.children

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#303]
We need a way to iterate over the contents of a Project as we can with Dataset, using the new Folders paradigm.

For Datasets we have this: https://github.com/Crunch-io/scrunch/wiki/User-Reference#children

So we'd want something like:

```python
for child in project.children:
    if isinstance(child, Dataset):
        print("I am dataset %s" % child.name)
    elif isinstance(child, Project):
        print("I am a project %s" % child.name)
```

**Comment by jjdelc** [comment]
Work done in https://github.com/Crunch-io/scrunch/pull/304
