### ISSUE TITLE
ds.fork(..., preserve_owner=False) doesn't work

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#306]
The `preserve_owner` kwarg on `ds.fork` doesn't seem to do anything. The default value is `False` which should mean the fork is created into the users Personal Project, however:

```python
>>> ds.owner
<Project: name='SSC Review'; id='ab5013...'>

>>> fk = ds.fork(preserve_owner=False)
>>> fk.owner
<Project: name='SSC Review'; id='ab5013...'>
```

**Comment by mathiasbc** [comment]
This is the default behaviour. What is happening is that when the owner of a Dataset if a Project, we are giving that priority and making the Project owner of the forked Dataset. Now, I can't say why are we doing that but it's documented and makes me think we had a good reason to add that.

https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L2272
https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L2298
https://github.com/Crunch-io/scrunch/blob/master/scrunch/tests/test_datasets.py#L1527

In the case we pass `preserve_owner=False` and the owner is not a Project, then the fork will live i the `Personal Project`.

@jjdelc or @xbito perhaps remember why we have this behaviour in place. I can quickly remove it if we no longer need this rule.

**Comment by jamesrkg** [comment]
Perhaps this kwarg is not well named and needs to be replaced with `preserve_project` (being `True` by default).

Here is what I see as the expected behavior based on the existing kwarg's name:

* ds owner is a project: 
  * `preserve_owner=True` -> fork is owned by the same project
  * `perserve_owner=False` -> fork is owned by the user forking it
* ds owner is a user:
  * `preserve_owner=True/False` -> either way fork is owned by the person forking it

So my confusion here is really based on the name of the `kwarg`. I'm not really interested in preserving the owner if it's a user (if I create a fork and don't want that fork to pollute ds' project, I'd say it's logical I be its owner, not whatever other random user owns ds).

Therefore, what about if we rename this kwarg to `preserve_project` with the following behavior:

* If ds owner is a user this kwarg is ignored (forking user becomes the fork's owner)
* if ds owner is a project:
  * `preserve_project=True` (the default) fork is also owned by ds' project
  * `preserve_project=False` forking user becomes the fork's owner

**Comment by mathiasbc** [comment]
I agree this is confusing. I am trying to figure the reason we make a Project prevail as the owner of the fork. If I find that there is no concrete reason then I think the most reasonable thing to do is simple remove that prevalence and respect the argument as it's passed.

I'm afraid changing an argument name will cause compatibility problems.

**Comment by jamesrkg** [comment]
I can live with that.

**Comment by jjdelc** [comment]
We are moving away from user owned datasets, soon all datasets will be always in a project (or a personal project).

Forking, by default will fork the dataset on the same project where the original dataset is. If you want it to be in a different project, you could fork with its `owner` being the target project where you want your fork to be.

**Comment by jamesrkg** [comment]
@jjdelc and in that case `owner=None` would cause it to end up in the forking users Personal Project?

**Comment by jjdelc** [comment]
should just avoid the `owner` attribute altogether and will end up in the user's Personal Project.

**Comment by jamesrkg** [comment]
@mathiasbc based on what @jjdelc has said it sounds like:

`preserve_owner=True` -> fork inherits owner from ds (leaving ds ownership types to Crunch)
`preserve_owner=False` -> nothing sent to API, sending the fork into the user's Personal Project

?

**Comment by mathiasbc** [comment]
@jamesrkg: yes, let me remove the part where we make Project owner prevail and make it simpler as ir should be. thanks for the chat.

**Comment by mathiasbc** [comment]
fixed at: https://github.com/Crunch-io/scrunch/pull/314
