### ISSUE TITLE
Creator of fork should be set as its current_editor

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#307]
If I create a fork I will typically need to follow up with immediately making edits to it, however that's not currently possible unless I follow up with `fk.change_owner(email)`, which feels unexpected (hence the `bug` tag).

```python
>>> fk = ds.fork()
>>> print fk.resource.body.current_editor
None
```

If this is a bug on the Crunch side I will send a ticket to support instead.

**Comment by mathiasbc** [comment]
taken care of in: https://github.com/Crunch-io/scrunch/pull/314
