### ISSUE TITLE
Variable.values

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#308]
The goal here is to see the ordered array of values held in a variable, e.g.:

```python
>>> ds[alias].values
[376
 984
 283
 575]
```

Given pandas is now an optional requirement we shouldn't use https://github.com/Crunch-io/pycrunch/blob/master/src/pycrunch/pandaslib.py directly but the pieces of the puzzle are in there to do this without it. 

Proposal:

```python
    @property
    def values(self):
        """
        Return the variable's values in a list.
        """
        url_values = self.resource.views['values']
        col = self.resource.session.get(url_values).payload['value']
        values = [
            None if (isinstance(item, dict) and list(item.keys()) == ['?']) 
            else item
            for item in col
        ]
        return values

```

I only added `@property` to keeps things simple but it isn't a deal-breaker. If we accepted this without it we could enhance it over time to return names for `categorical` instead of `id`, for example.

The above works well:

```python
>>> ds['caseid'].values
[323580271.0,
 323580340.0,
 323580355.0,
 323686601.0]

>>> ds['single'].values
 2,
 3,
 None,
 None,
 3]

>>> ds['multiple'].values
[[{u'?': 9}, {u'?': 9}, {u'?': 9}, {u'?': 9}],
 [{u'?': 9}, {u'?': 9}, {u'?': 9}, {u'?': 9}],
 [{u'?': 9}, {u'?': 9}, {u'?': 9}, {u'?': 9}],
 [{u'?': 9}, {u'?': 9}, {u'?': 9}, {u'?': 9}]]

>>> ds['calendar'].values
 u'2007-07-17',
 u'2007-07-23',
 u'2007-07-11',
 None,
 u'2007-07-12',
 None]
```

Etc.

One question about this @jjdelc @malecki: is it definitely the case that the `https://app.crunch.io/api/datasets/.../variables/.../values/` endpoint reflects the order of the dataset at that time? One of the ways this method would be used is in conjunction with [`create_variable`](https://github.com/Crunch-io/scrunch/wiki/User-Reference#create_variable) when working out what order to send the values in.

**Comment by jjdelc** [comment]
The best way to create a new variables based on the values of another variable is to use the `copy_variable` function. Will create a derived variable that reflects the values of the original. That is that changes on the original will be seen on the derived one.

It is possible to make a material copy of the variable, again using the same `copy_variable` function, but indicating `derived=False` on the payload, which will make an unlinked copy of the variable with independent copy of the values.

I would advice against just fetching the values for a column since it can be in the millions and will be a big performance hit on the API. The `/values/` endpoint supports pagination so that could be used to take a peek at the values.

**Comment by jamesrkg** [comment]
@jjdelc the use case mentioned isn't about creating a copy of a variable, but rather uploading a single vector of values into a new variable in the correct order. For example: to add a new weight or segmentation variable for which the values have been calculated outside of Crunch. The alternative is of course to import said data into a new dataset, join it to the targeted dataset, then delete the imported temporary dataset but that is quite a cumbersome work-around. Something more direct would be preferable if that is possible.

**Comment by jjdelc** [comment]
In that case, the `/variables/` endpoint does accept a `values` argument in its payload, which can be a list of values that the new column will have. Naturally has to match length. But I don't think it will fork for too big columns as you may hit a payload size limit (unsure where that is). 

The order of the values would be the same as insertion order for the rows.

**Comment by jamesrkg** [comment]
@jjdelc how can we find out what the payload size limit is? If there is one we should account for it somehow (chunking if possible and/or a `UserWarning`).

**Comment by jjdelc** [comment]
The configured upload limit is 100MB (for the full JSON payload). So whatever values you can fit there will be the biggest column size you can add with discrete values.
