### ISSUE TITLE
Variable.edit(uniform_basis)

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#309]
Can we please add `uniform_basis` to `Variable`'s list of `_MUTABLE_ATTRIBUTES`?

https://github.com/Crunch-io/scrunch/blob/1b5074e841c7b70bdf75df0613a8bd41a27543a3/scrunch/datasets.py#L2640-L2641

Right now we are doing this manually using:

```
ds._reload_variables()
var = var.resource.edit(uniform_basis=False)
```

**Comment by mathiasbc** [comment]
Resolved in: https://github.com/Crunch-io/scrunch/pull/314. closing since it's a pretty straightforward ticket.
