### ISSUE TITLE
uniform_basis

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#311]
Related to #309, would it be possible to include a kwarg for `uniform_basis` into [derive_multiple_response](https://github.com/Crunch-io/scrunch/wiki/User-Reference#derive_multiple_response) and also [create_categorical(..., multiple=True)](https://github.com/Crunch-io/scrunch/wiki/User-Reference#create_categorical) so that a subsequent edit for this attribute doesn't need to be done separately?

E.g.:

```python
>>> var = derive_multiple_response(..., uniform_basis=False)
>>> var = create_categorical(..., multiple=True, uniform_basis=False)
```

I personally think that the default value for this kwarg should be `False`. Is there an argument against that at all?

**Comment by mathiasbc** [comment]
https://github.com/Crunch-io/scrunch/pull/314
