### ISSUE TITLE
NO_DATA_ID should be -1

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#313]
`NO_DATA_ID` need to be changed to `-1`. Although this is apparently now being changed automatically on the server, we should keep this process in synch with what Crunch expects/applies.

https://github.com/Crunch-io/scrunch/blob/1b5074e841c7b70bdf75df0613a8bd41a27543a3/scrunch/helpers.py#L11-L13

**Comment by mathiasbc** [comment]
https://github.com/Crunch-io/scrunch/pull/314
