### ISSUE TITLE
Dataset attributes

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#316]
We already have a number of attributes available directly to the class, however there are more of them:

https://docs.crunch.io/endpoint-reference/endpoint-dataset.html?highlight=archive#get

Can we either add all of them or add a method such as:

```python
def attrib(self, name):
    return self.resource.body.get(name)
```

**Comment by mathiasbc** [comment]
I added size to the Set of `_IMMUTABLE_ATTRIBUTES`. All the other attributes should be there, have a property to get/set them or in the case of `streaming` it is implied by the BaseDataset subclass.

What other attribute would you like to get access to ?

**Comment by jamesrkg** [comment]
It looks like the ones that are still missing are:

* permissions
* owner_id
* owner_name
* streaming
* current_editor
* current_editor_name

**Comment by mathiasbc** [comment]
In that order, these attributes are exposed in the following:

- Indirectly but `add_user` let's you change permissions for a given user
- `change_owner` method and `owner` property
- `change_owner` method and `owner` property
- streaming is directly inferred from MutableDataset and StreamingDataset. Not intended to be changed by the users.
- `change_editor` method and `editor` property
- `change_editor` method and `editor` property

If you feel we should offer more fine grained control I'd be happy to help but I know there is a reason we are currently doing it like this. @jjdelc @xbito

**Comment by jamesrkg** [comment]
Right, ok thanks @mathiasbc .
