### ISSUE TITLE
Dataset.archive()

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#317]
https://docs.crunch.io/endpoint-reference/endpoint-dataset.html?highlight=archive#drafts

We would want the ability to archive or unarchive a dataset, so presumably something like `ds.archive(True)` and `ds.archive(False)`.

Alternatively, should this be handled by `Dataset.edit` as one of the `_BASE_MUTABLE_ATTRIBUTES`?

**Comment by mathiasbc** [comment]
I think like any other mutable attribute we should do it with the `edit` method. This is pretty simple: `ds.edit(archived=True|False)` so I'm gonna close and copy Fernando here in case he thinks it's best to have a helper method.
