### ISSUE TITLE
Should we cache the result of the variables endpoint?

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#32]
Right now a typical session if we edit some variables in scrunch looks like this:

DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): alpha.crunch.io
DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/ HTTP/1.1" 401 170
DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "POST /api/public/login/ HTTP/1.1" 204 0
DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/ HTTP/1.1" 200 430
DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/datasets/ HTTP/1.1" 200 325314
DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/datasets/2641baf9b9a8478da4bf98b58026217f/ HTTP/1.1" 200 757
dataset ID 2641baf9b9a8478da4bf98b58026217f
dataset name testing_fork_xbito

DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/datasets/2641baf9b9a8478da4bf98b58026217f/variables/ HTTP/1.1" 200 13679
DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/datasets/2641baf9b9a8478da4bf98b58026217f/variables/000436/ HTTP/1.1" 200 668

A categorical variable Average Pay | Average Pay
ID 000436

DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/datasets/2641baf9b9a8478da4bf98b58026217f/variables/ HTTP/1.1" 200 13679
DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/datasets/2641baf9b9a8478da4bf98b58026217f/variables/000407/ HTTP/1.1" 200 922

A categorical array variable Average Pay | Pay by Job
ID 000407

DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/datasets/2641baf9b9a8478da4bf98b58026217f/variables/ HTTP/1.1" 200 13679
DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/datasets/2641baf9b9a8478da4bf98b58026217f/variables/000115/ HTTP/1.1" 200 479

A text variable Party ID (other)
ID 000115

DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/datasets/2641baf9b9a8478da4bf98b58026217f/variables/ HTTP/1.1" 200 13679
DEBUG:requests.packages.urllib3.connectionpool:https://alpha.crunch.io:443 "GET /api/datasets/2641baf9b9a8478da4bf98b58026217f/variables/000063/ HTTP/1.1" 200 500

A numeric variable Birth Year
ID 000063

Should we cache the variables result? I think the R crunch library does so. Of course then it becomes a problem determining how and when to invalidate that cache.

**Comment by jjdelc** [comment]
Can we see the interactions that caused this? If it is each time a variable is fetched by alias, we could cache that for that reason, just for the lookup, but be careful with other caches.

It would require our code to limit the paths we take to create/delete variables since those would need to bust cache.

My gut reaction is to avoid caching, but I'd like to see the script that causes this and if we're getting the full catalog each time only to get a variable, maybe we could help that single use case.

**Comment by nealrichardson** [comment]
The R package uses a query cache more generally, which has proven to be a real performance win and made development easier too. Our API is well structured and there are very few requests that have side effects that make cache invalidation challenging. Concurrent editing would be one other source of complexity, but that's mostly disallowed. 

The R query cache library is https://github.com/nealrichardson/httpcache (super elegant, if i may say so myself ;), and you can grep for calls to `dropCache` in the rcrunch package to see the few places where the general cache invalidation rules have to be supplemented.

**Comment by mathiasbc** [comment]
In https://github.com/Crunch-io/scrunch/pull/61 We added a way of instantiating Variable with the need of Shoji entity and just with Shoji Tuple. Perhaps we could work around that for this particular issue ?

**Comment by mathiasbc** [comment]
What kind of technique can we use for caching variables call ?

**Comment by mathiasbc** [comment]
Closing because the current approach does not need rounds-trips to Crunch for variables and subvariables.
