### ISSUE TITLE
How are we going to expose Dataset settings?

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#33]
Right now there are 3 settings:

viewers_can_export
viewers_can_change_weight
weight

We are not going to touch weights yet, but the two other flags do seem like something we would want to be able to set and read from scrunch. Shall we do something so them can be set directly from the dataset object as attributes or do we want a settings attribute that can access those settings as members?

dataset.viewers_can_export
vs
dataset.settings['viewers_can_export']

The latter has the advantage that if new settings appear no new code is needed.

**Comment by jjdelc** [comment]
I back the .settings attribute for handling them. 

How would these attributes be changed? Your proposal is good for read, but regarding writing? If .settings is just a dict (as it is returned from the API) then doing dataset.save()? or something similar would perform the the writing of all the dataset attributes.

**Comment by xbito** [comment]
Wouldn't it have to be dataset.settings.save(), I don't like that it moves away from the style we have been imposing with variables and datasets having an edit method to edit their attributes. Maybe then dataset.settings should be an object of a DatasetSettings class that also has an edit method? I know class proliferation might be something we don't want, but it would turn up to be confusing to have some parts of the api behave in some way and other parts in another.

**Comment by xbito** [comment]
We will a read-only dictionary for dataset.settings and we will add a dataset.change_settings method with 2 possible arguments, corresponding to viewers_can_export or viewers_can_change_weight

**Comment by alejandro-rivera** [comment]
This has been addressed in https://github.com/Crunch-io/scrunch/commit/f2fb39acebec3279cf4eada57030b6204ce70606
