### ISSUE TITLE
load_savepoint should _reload_variables()

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#341]
Following these steps, an unknown alias error is thrown:

1. create savepoint
2. delete variable
3. reload savepoint
4. reference deleted savepoint

The fix will be to add a `self._reload_variables()` at the end of this method:

https://github.com/Crunch-io/scrunch/blob/35ca782a7dec6b195c221f50a7ec783bb9090751/scrunch/datasets.py#L1888-L1906

**Comment by xbito** [comment]
Going to be handled by @anderstheet

**Comment by xbito** [comment]
Should be solved already.
