### ISSUE TITLE
ds.sort()

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#345]
In order to make reliable use of the `duplicates()` expression method we need to be able to sort the rows of a dataset. An example need for this would be to exclude duplicates after prioritizing version and/or period of the survey that was taken.

If possible we would also need the ability to elect ascending/descending as appropriate.

In this it makes sense, if possible, to sort using a list of variables, e.g.:

```
ds.sort('version', descending=True)
ds.sort(['version', 'period'], descending=False)
```

**Comment by xbito** [comment]
@jamesrkg I'm not sure if you are expecting this to be something executed in the dataset in crunch? If that is the case then there should be an equivalent crunch API right? I have searched the document for any sort or order for rows and haven't been successful. Maybe I'm looking at the wrong place though, @jjdelc is there such an API?

**Comment by jjdelc** [comment]
We don't support sorting of rows in the API. The way to calculate duplicates is by doing summaries or cubes on the data, anything with count >1 has duplicates.

**Comment by jamesrkg** [comment]
@jjdelc we don't need to calculate how many duplicates there are, but rather we want to be able to add an exclusion based on duplicates. However, excluding rows on `duplicates` works by excluding the 2nd and subsequent instances encountered in the order of the rows from the top to the bottom. This means you can't control _which_ duplicate is kept. For example you may prefer to keep the second duplicate and discard the first, because the second one completed the correct version of the survey.

**Comment by jjdelc** [comment]
Ah, I see what you mean. No there is no way to control which duplicates are kept, the function takes a single argument that is the column, in insertion order. And I'm afraid we don't have a sorting expression to pass in :-/
