### ISSUE TITLE
`Dataset.create_variable` raises KeyError without specifying an alias

### ISSUE THREAD

**Issue by skriems** [Crunch-io/scrunch#355]
... which shouldn't happen according to the docstring. And in fact the variable is created but it seems the refresh is not doing what it's supposed to do.
https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L889
```
(Pdb) dataset.create_variable('datetime', 'datetime', resolution='ms')
...
*** KeyError: 'alias'
(Pdb) 
```

**Comment by mathiasbc** [comment]
https://github.com/Crunch-io/scrunch/commit/59d64a0313178de1b838cd9377fbf52726681fa9
