### ISSUE TITLE
Moving dataset into nested project throws 400

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#356]
For example:

```
>>> pr = scrunch.get_project('APAC|Singapore|Client Folder')
>>> ds.move(pr)
(<Response [400]>, 'https://app.crunch.io/api/projects/.../', {u'status': u'400 Bad Request', u'message': u'Invalid graph: must contain all index items'})
```

However, I can move it without an error if I don't try to move it into a nested project (then I move it into the targeted nested project using the UI):

```
>>> pr = scrunch.get_project('APAC')
>>> ds.move(pr)
```

The same happens with the (now deprecated) `pr.move_here(ds)`.

@jjdelc any ideas?

Tagging @alextanski

**Comment by alextanski** [comment]
It might be a red herring but while I was replicating that error @jamesrkg cleaned the UK project from a massive amount of datasets (now archived) and the 400 went away for me. This could point towards the error being tied to big/complex/deep nested projects.

**Comment by alextanski** [comment]
I can also confirm that in very small projects (TechOps for example) nested moves are working, no 400 here:
`Dataset 'Media_Lab_Sue_Ryder merged [Test KM] [FNT 37 Merge]' now located in project 'TechOps|Alex'`.

**Comment by jjdelc** [comment]
Given the error message, it looks like a partial `graph` was sent in. Could it be the case that two people were moving things in the project at the same time? In such case, one would read a past version of `graph`, then the next person make an update, and when you try to send it in again you'd get that 400.

**Comment by jamesrkg** [comment]
@jjdelc I don't believe that explains this situation because after someone reported the problem to me (following 4 separate attempts) I tried independently and also saw the same error.

**Comment by jamesrkg** [comment]
@jjdelc wouldn't this:

https://github.com/Crunch-io/scrunch/blob/f4830cbcef9c4994c2fc106fa8996fa2f4b05893/scrunch/datasets.py#L672

Make mean the situation you described, while not strictly impossible, would be *extremely* rare - definitely not something that could happen 5 times in a row attempted by more than one person?

**Comment by jjdelc** [comment]
Another option, given that that was a really large project, could be that internally (in our db) the list of members of the project and the graph storing their order got out of sync. In such case it could have errored but get auto-synced and then work on the following same request.

**Comment by jamesrkg** [comment]
With the original example we tried (at least) 5 times over a period of about 10 minutes and all failed until I switched to working with only the top-level root project. It failed every time we were attempting with a nested project.

**Comment by alextanski** [comment]
Given theory 1 (partial graph due to outdated project content) would be true, would moving a project _after manually deleting a dataset from the target subfolder_ lead to the error? I just did that (created a dataset, went to the web app, deleted a dataset from my subfolder, then went back and moved) - it went through without error.

**Comment by alextanski** [comment]
bump.
This error comes up and up again for moving directly to nested folders.

**Comment by jjdelc** [comment]
@mathiasbc  I think we can get around this, by not sending the `graph` in the `PATCH` when no position arguments have been given.
https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L589

```
kwargs = {"index:" : {....}}
if {position, before, after} != {None}:
    # Some of the positional args was not None
    graph = self._position_items(items, position, before, after)
    kwargs["graph"] = graph
self.resource.patch(shoji_entity_wrapper({}, **kwargs)
```

That way, we avoid trying to send the `graph` when the user doesn't care. It is not truly a fix for the underlying problem (as it's difficult to debug), but we can avoid hitting it by not sending the graph (that may be out of sync) when users aren't caring for it.
