### ISSUE TITLE
get_exclusion not rendering correctly?

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#358]
I think there might be a problem with the way `get_exclusion` renders the exclusion on a dataset:

```python
>>> conn.ds.exclude('(disposition != 1 or missing(disposition)) or missing(gender) or missing(age) or age <= 18 or not race in [1, 2, 3, 4]')
>>> conn.ds.get_exclusion()
u'(disposition != 1 or missing(disposition)) or (missing(gender) or (missing(age) or (age <= 18 or not race in [1, 2, 3, 4])))'
```

**Comment by jamesrkg** [comment]
I can confirm that using rcrunch the correct exclusion on this dataset is returned:

```R
exc
Crunch logical expression: disposition != "Complete" | is.na(disposition) | is.na(gender) | is.na(age) | age <= 18 | !race %in% c("Chinese", "Malay", "Indian", "Other")
```

FYI this dataset is f1be983eaacd409f8465a538f2c2bec3.

**Comment by xbito** [comment]
Isn't it logically the same? We group/add the parenthesis because of how expressions are done in Crunch.

**Comment by jamesrkg** [comment]
Sorry, I thought this would compound it returned to the API but did some more tests and it looks fine after all. Sorry for the false alarm!
