### ISSUE TITLE
Prevent the Dataset.order property from getting out of sync

### ISSUE THREAD

**Issue by alejandro-rivera** [Crunch-io/scrunch#36]
Currently, the `order` property that represents the Dataset's **hierarchical order** structure is prone to getting out of sync with regards to the actual structure stored in Crunch.

This is because once the `order` property is loaded for the first time, no further checks are performed to ensure the freshness of the data. Therefore, we need to find a way to ensure that the `order` property is always in sync.

Unfortunately, loading the full structure from Crunch _everytime_ the `order` property is accessed would be far too costly for Datasets with lots of variables. So that's definitely a no-no.

Ideally, the Crunch API could provide support for [ETags](https://en.wikipedia.org/wiki/HTTP_ETag) in the **hierarchical order** endpoint of a Dataset (`/api/datasets/{dsid}/variables/hier/`), so that the **scrunch** library would only fetch the structure from Crunch when it would be truly needed. Of course, that would require help from @nealrichardson et al. at Crunch.

For the time being, we could use the Dataset's `modification_time` field as an indicator of whether to re-load the **hierarchical order** structure from Crunch, given that this field is updated whenever the structure changes. The downside is that many other changes to the Dataset also update the `modification_time` field, making this a less-than-ideal solution. At least it's better than re-loading the full structure from Crunch on every access to the `order` property.

Feedback and further suggestions are highly appreciated.

**Comment by nealrichardson** [comment]
Option 1: query caching of some form, as discussed on another ticket. It's not hard to keep the variable order in sync with the variable catalog; the only events that change it are (a) a PUT request to change the order, (b) a POST to the variable catalog to add a new variable, and (c) a DELETE to a variable entity. So it's easy to know when you need to pull a fresh copy of the order.

Option 2: if you really don't trust that the current Python session is the only active user who could be altering the variable order, you can compare mod_time like you say, or do what the web app does, which is poll the dataset's `state/` endpoint, which returns similar information (and may in the future have more disaggregated information about which things have changed). 

ETags could be nice, but we've made it 4+ years doing a combination of the two options I described here, so I don't think they're strictly necessary to make scrunch work.

**Comment by alejandro-rivera** [comment]
Thanks for the insightful suggestions @nealrichardson. Using the `revision` field in `state/` looks very promising for this purpose.

For the sake of completeness, here's a simple example of how the `order` property can get out of sync (assuming all the scrunch bits have been already imported):

```python
ds = get_dataset('abc123')
ds2 = get_dataset('abc123')
ds['|'].insert('myvar')
```

After this, only `ds.order` contains the proper structure; `ds2.order` is out of sync.

**Comment by xbito** [comment]
What is worse is that:

ds = get_dataset('abc123')
ds['myvar'].move('|')

can also generate a ds that is out of sync because the ds['myvar'] Variable instance receives not the reference to the ds object, but a copy of the ds.resource and then generates its own Dataset object from it, this is to avoid circular references and memory leaks (per Jj recommendation).

**Comment by jjdelc** [comment]
That is a different problem. This is because you're handling two copies of the data in memory. That will happen chronically in all your code.

```
ds = get_dataset('X')
x1 = ds['X']
x2 = ds['X']
x1.name = "not x"
x1.save()
x2.save()
assert ds['X'].name != "not x"
```

I don't think that this is a problem of keeping orders in sync but the understanding of the library. It is the same situation as with ORMs.

**Comment by nealrichardson** [comment]
Ok. Sure. But that seems like a silly case to design a solution for. Who would do that? What practical end does loading two copies of the same dataset accomplish?

I would say that if a user wants to do that, they need to understand that they are creating objects that can get out of sync with each other, and they should be responsible for refreshing them to keep one in sync if they choose to alter the other. If someone were to do this, surely they would have a reason for making copies of their objects, and they'd know they need to keep up with them.

**Comment by nealrichardson** [comment]
@jjdelc your example also looks like user error to me.

**Comment by jjdelc** [comment]
That was what I wanted to show, it can happen with any entity that we read from the persistence layer as parallel in-memory copies and don't keep proper track of them.

**Comment by xbito** [comment]
@jjdelc that's not even real scrunch code?
