### ISSUE TITLE
ds.add_user(team)

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#369]
Extend support for `ds.add_user` to share with a Team.

```python
my_team = scrunch.get_team("My team")
ds.add_user(my_team, edit=False)
```

**Comment by mathiasbc** [comment]
@jamesrkg: this method is deprecated and instead it suggests using `self.members.add` which supports teams: https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L378

**Comment by jamesrkg** [comment]
No problem @mathiasbc , I think this ticket was created before I made the switch.
