### ISSUE TITLE
Support CRUNCH_API_KEY env/config var

### ISSUE THREAD

**Issue by adblair** [Crunch-io/scrunch#431]
Currently scrunch looks for CRUNCH_USERNAME and CRUNCH_PASSWORD in the environment or config file, but as far as I understand user/pw auth is going away imminently. Please can you add support for CRUNCH_API_KEY too, so that apps using this approach to specifying auth may continue to work?

**Comment by andrepedroso** [comment]
+1

**Comment by anderstheet** [comment]
+1

**Comment by AlasdairE** [comment]
+1

**Comment by chrisBrookes93** [comment]
+1

**Comment by mrakinola** [comment]
+1

**Comment by adblair** [comment]
@anderstheet Yes, CRUNCH_API_KEY works with 0.12.0, thanks!
