### ISSUE TITLE
Protect categories from derived variables

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#49]
Editing categories from derived variables is potentially disruptive for the derivation itself. It makes much more sense to simply recreate the variable with the new categories and new instructions on how to derive the variable.

So lets disable edits to categories for derived variables.

**Comment by jjdelc** [comment]
Here's the PR with the changes, the previous implementation was wrong and needed fixing too.
https://github.com/Crunch-io/scrunch/pull/50/files

**Comment by xbito** [comment]
Done! :)
