### ISSUE TITLE
Add metadata to scrunch's ds.export()

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#51]
Please add support to save the dataset metadata when using ds.download().

For example I changed the signature and added the following to the top of download method:

    def download(self, path, path_metadata=None, filter=None, variables=None, hidden=True):
        """
        Downloads a dataset as CSV to the given path.
        this includes hidden variables and categories
        as id's.
        """
        if not path_metadata is None:
            metadata = self.resource.table['metadata']
            if not variables is None:
                metadata = {
                    key: value
                    for key, value in metadata.iteritems()
                    if value['alias'] in variables
                }
            with open(path_metadata, 'w+') as f:
                json.dump(metadata, f, sort_keys=True)
 
Importantly the metadata should be filtered to retain only those variables specified by the variables parameter (if any).

**Comment by xbito** [comment]
This has been submitted on behalf of Jamie replacing an internal fogbugz ticket.

**Comment by nealrichardson** [comment]
Why is this called `download` instead of `export` as it is everywhere else in Crunch? And why not support SPSS format and the other export options we have (that users have been requesting)?

**Comment by xbito** [comment]
Opened other tickets to tackle your comment Neal.

**Comment by jamesrkg** [comment]
Can you please also add the `rules` from the `fragments : missing_rules` endpoint to all variable/subvariable meta for completeness?

E.g. `"rules": {"skipped": {"value": 8}, "not asked": {"value": 9}}` or `"rules": {}` (for no missing rules).
