### ISSUE TITLE
Add SPSS to export (currently download) and other options

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#53]
Not really sure which other options, but Crunch devs must be aware of them.

https://github.com/Crunch-io/scrunch/issues/51#issuecomment-277372641

**Comment by alejandro-rivera** [comment]
This has been solved in https://github.com/Crunch-io/scrunch/commit/46b3e9d5bcf4dec4cc9038440682615f4c09c1b9.

SPSS support has been added by means of the `format` argument in the `download` method, which can be either `'csv'` (default) or `'spss'`.

Additionally, the `options` argument in the `download` method allows providing a dictionary object with which the same export options as in the Crunch UI can be configured. The default values are:

```python
# For CSV exports:
options = {
    'use_category_ids': True
}

# For SPSS exports:
options = {
    'prefix_subvariables': False,
    'var_label_field': 'description'
}
```
