### ISSUE TITLE
RIM weighting API

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#57]
Add method/s to the `Dataset` class to run RIM weights based on a given profile. There are a few parts to this. The following are examples of requirements, not necessarily API drafts.

1. Define the weight profile:

```python
weight_targets = [
    {'gender' : {
        1: 45, 
        2: 55}},
    {'locality': {
        1: 10, 
        2: 15, 
        3: 20, 
        4: 25, 
        5: 30}}
]
```

2. Define weight groups using filters::

```python
.add_group(
    name='W1',
    targets=weight_targets,
    filter_def='Wave==1')

.add_group(
    name='W2',
    targets=weight_targets,
    filter_def='Wave==2')
```

3. Define weight group proportions:

```python
.group_targets({
    "W1": 20,
    "W2": 20,
    "W3": 20,
    "W4": 20,
    "W5": 20})
```

4. Specify the overall targeted weighted base:

```python
.total = 7500
```

5. Running the weights

```python
.run()
```

6. Provide access to a weight report:

```python
Weight variable        weights_foo                                                    
Weight group                    W1           W2           W3           W4           W5
Weight filter              Wave==1      Wave==2      Wave==3      Wave==4      Wave==5
Total: unweighted      1621.000000  1669.000000  1689.000000  1637.000000  1639.000000
Total: weighted        1500.000000  1500.000000  1500.000000  1500.000000  1500.000000
Weighting efficiency     51.651655    50.069772    53.208626    51.492525    50.382047
Iterations required      12.000000    14.000000    11.000000    10.000000    10.000000
Mean weight factor        0.925355     0.898742     0.888099     0.916310     0.915192
Minimum weight factor     0.242618     0.230671     0.230002     0.219601     0.234185
Maximum weight factor     2.724011     2.922364     2.559280     2.873776     2.842260
Weight factor ratio      11.227557    12.668975    11.127188    13.086321    12.136803
```

**Comment by jamesrkg** [comment]
@xbito @jjdelc can we bring this back onto the radar? It's not a blocker for me right now but I suspect it's something that will come up as such before the end of the year. Unsure if the above examples closely resemble actual API use cases, so please don't take them as a rigid requirements spec.

I also understand that the weighting API allows a threshold to be set ahead of time such that when a certain number of cases have been achieved, the weights will be generated automatically and that the weights can continually be re-generated after that point. I'm unsure how this works so can't suggest anything yet. Let's discuss.

**Comment by jjdelc** [comment]
I think that @malecki is the person to help here, he's much more familiar with the cubes/weight API inputs and parameters than me on how to design this.

**Comment by teresarasmussen** [comment]
For R we use this script to match the weight created in either QP or Dim.

# Weight script on matrix variable created in Crunch (GenAgeRegion_v3)
library(survey)
ds$GenAgeRegion_v3 <- interactVariables(ds$region_DK, ds$profile_age_rc, ds$gender, sep="_", name="GenAgeRegion_v3")
categories(ds$GenAgeRegion_v3)
GenAgeRegion_v3 <- as.vector(ds$GenAgeRegion_v3) #load as local variable
weighted <- !is.na(GenAgeRegion_v3) # logical
df <- data.frame(GenAgeRegion_v3 = GenAgeRegion_v3[weighted])
pop.list <- list(data.frame(GenAgeRegion_v3=levels(df$GenAgeRegion_v3), 
                            Freq=c(4.9461,1.4793,2.4926,3.0542,1.2582,4.0483,1.7929,2.5102,2.7106,1.1518,
                                   3.5361,1.9461,2.7176,2.7370,1.3065,3.6959,2.1205,2.9183,2.7935,1.4093,
                                   4.8184,1.6227,2.7042,3.2405,1.4328,4.0843,1.7727,2.5394,2.7656,1.1937,
                                   3.5001,1.9420,2.7392,2.7535,1.3134,2.9032,1.8374,2.5281,2.4387,1.2453)))
svy <- svydesign(id=~1, data=df, probs=~1)
raked <- rake(svy, control=list(maxit=200, epsilon=1e-7),
              sample.margins=list(~GenAgeRegion_v3), population.margins=pop.list)
wgt <- stats::weights(raked)  # grabs actual weights from object 'raked'
wgt <- wgt/mean(wgt)  # normalize weights
tmp_wgt <- rep(NA, nrow(ds))  # created empty vector of NAs
tmp_wgt[weighted] <- wgt  # assign values where have a weight
ds[['weight_r3']] <- tmp_wgt  # send tmp_wgt up to Crunch. Note, weights not applied to the data yet.
weight(ds) <- ds$weight_r3 # Now weights applied to the data
settings(ds)$viewers_can_change_weight <- FALSE

#Summaries
summary(tmp_wgt)

tab1 <- crtabs(~ gender, data=ds) #show weighted data if weight variable is enabled
round(100*prop.table(tab1), digits = 2)
tab2 <- crtabs(~ profile_age_rc, data=ds)
round(100*prop.table(tab2), digits = 2)
tab3 <- crtabs(~ region_DK, data=ds)
round(100*prop.table(tab3), digits = 2)

bases(tab)

This survey has the original weight "weights_CUSTOM" from QP plus the created weight in R "Weight_r3"

**Comment by jamesrkg** [comment]
@jonkeane you might have some advice on how to proceed here. It's not clear yet what the API offers within/beyond the examples given at the top of the ticket. To be clear, those examples were given only to get the conversation going. This ticket is actually just about extending coverage in scrunch to what is already offered by the Crunch. We'll look beyond that, if needed, in separate tickets.

**Comment by jamesrkg** [comment]
API reference: https://docs.crunch.io/feature-guide/feature-deriving.html?highlight=rake#weights

**Comment by xbito** [comment]
Reassigning to Jamie for testing when he comes back.
