### ISSUE TITLE
(derived) Support "else" case for new categoricals 

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#63]
Extend support for the Crunch API's `else` case to `create_single_response` and `create_multiple_response`.

For example `'id': 6`, below:

```python
agerange = dataset.create_categorical([
    {'id': 1, 'name': 'Underage', case: 'age < 18'},
    {'id': 2, 'name': 'Millenials', case: 'age > 18 and age < 25'},
    {'id': 3, 'name': 'Gen X', case: 'age < 35 and age >= 25'},
    {'id': 4, 'name': 'Grown ups', case: 'age < 60 and age >= 35'},
    {'id': 5, 'name': '60+', case: 'age >= 60', 'numeric_value': 100},
    {'id': 6, 'name': 'Unknown', case: 'else'}
], alias='agerange', name='Age range', multiple=False)
```

**Comment by jamesrkg** [comment]
For `categorical` it looks like the the final ELSE is supported here:

http://docs.crunch.io/feature-guide/feature-deriving.html?highlight=else#case-statements

I don't think an example of the ELSE is actually given in that snippet, though. If I read it correctly, _"You may include an extra value for the case when none of the boolean expressions match"_ means `derivation.args` would have a fourth item `{"value": 4}` in order to code non-conforming rows to `Other`?

Given what we've done for #286 we'll also need to consider how this could support derived `multiple_response` as well. `derive_multiple_response` should stay in its current raw form so this would only be an extension to `create_categorical(..., multiple=True)`. Since we're talking about a series of case statements for distinct subvariables I'm fairly sure scrunch will need to stitch all the `cases` together with `not X and not Y and not ...` etc., so that the following:

```python
var = ds.create_categorical(
    name='Preferred soda',
    alias='soda',
    description='Which drinks do you prefer?',
    multiple=True,
    categories=[
        {'id': 1, 'name': 'Coke', 'case': 'q1 in [1]', 'missing': 'missing(q1)'},
        {'id': 2, 'name': 'Pepsi', 'case': 'q1 in [2]', 'missing': 'missing(q1)'},
        {'id': 4, 'name': 'Coke or Pepsi', 'case': 'q1 in [1,2]', 'missing': 'missing(q1)'},
        {'id': 3, 'name': 'Other brands', 'case': 'q1 in [3, 4, 5, 6, 95]', 'missing': 'missing(q1)'},
        {'id': 5, 'name': 'Does not drink soda', 'case': 'else', 'missing': 'missing(screener4)'}
    ]
)
```

Produces this for `derive_multiple_response`:

```
[
    {
        "id": 1, 
        "name": "Coke",
        "cases": {
            "1": "q1 in [1]", 
            "2": "not (q1 in [1]) and not (missing(q1))", 
            "3": "missing(q1)"
        }
    }, 
    { 
        "id": 2, 
        "name": "Pepsi",
        "cases": {
            "1": "q1 in [2]", 
            "2": "not (q1 in [2]) and not (missing(q1))", 
            "3": "missing(q1)"
        }
    }, 
    {
        "id": 4, 
        "name": "Coke or Pepsi",
        "cases": {
            "1": "q1 in [1,2]", 
            "2": "not (q1 in [1,2]) and not (missing(q1))", 
            "3": "missing(q1)"
        }
    }, 
    {
        "id": 3, 
        "name": "Other brands",
        "cases": {
            "1": "q1 in [3, 4, 5, 6, 95]", 
            "2": "not (q1 in [3, 4, 5, 6, 95]) and not (missing(q1))", 
            "3": "missing(q1)"
        }
    }, 
    {
        "id": 5, 
        "name": "Does not drink soda",
        "cases": {
            "1": "not (q1 in [1]) and not (q1 in [2]) and not (q1 in [1,2]) and not (q1 in [3, 4, 5, 6, 95])", 
            "2": "not (not (q1 in [1]) and not (q1 in [2]) and not (q1 in [1,2]) and not (q1 in [3, 4, 5, 6, 95])) and not (missing(q1))", 
            "3": "missing(q1)"
        }
    }
]
```

**Comment by mathiasbc** [comment]
There are some issues here. First, for creating categoricals. I can't guess how to use the `else` case in the derivation expression: https://docs.crunch.io/feature-guide/feature-deriving.html?highlight=else#case-statements.

But I could build it by simple negating and concatenating all the previous categories. This would work. Now, if we intend to have an `else`, which implies a default to all not previously matched cases, then `missing` should be mutually exclusive with the `else` right ? 

Then, similar case for Multiple Response, `missing_case` should not be allowed for subvariables. It is my understanding that having and else and a `missing_case` could cause overlapping expressions.

**Comment by mathiasbc** [comment]
WIP: https://github.com/Crunch-io/scrunch/pull/321

**Comment by jamesrkg** [comment]
@mathiasbc i've updated the example with the changes we discussed. The basic logic is:

**Where missing is not given for the else:**
* the implied selected case for the else is: `not (any of the explicit selected cases)`
* the implied not selected case is: `(any of the explicit selected cases)`

**Where missing is given for the else:**
* the implied selected case for the else is `not (any of the explicit selected cases)`
* the implied not selected case is `(any of the explicit selected cases) and not (else's missing)`
* the missing case is given explicitly

**Comment by mathiasbc** [comment]
@jamesrkg: the pull request should be done now. I added a lot of tests but please test that we are getting what we expect to get.
