### ISSUE TITLE
Include examples how to use the crunch.ini file

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#66]
The (google) docs have description about how to write a crunch.ini file, but it is not really clear where it should be, and most importantly, there are no code examples how to use it.

People might be thinking they still need to use connect, or write something like connect("DEFAULT") or connect("crunch.ini").

It should be clear that once the crunch.ini file is there or the environment variables are there, people can start using get_dataset directly.

**Comment by mathiasbc** [comment]
Updated docs for this.
