### ISSUE TITLE
Support for the Crunch multitable API

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#71]
Add helper/s to extend the multitable API to scrunch. A general overview of this would include:

* Build a new multitable (assign side/top variables)
* Manage a tab book (create, add to, remove from, save, share, etc.)
* Set multitable properties for the UI
* Render multitable as pandas DataFrame (or provide as JSON blob readable by pandas, details to follow)
* Export multitable/tabbook to local XLSX

**Comment by mathiasbc** [comment]
progress can be followed here: https://github.com/Crunch-io/scrunch/tree/feature/multitables

**Comment by mathiasbc** [comment]
Initial PR: https://github.com/Crunch-io/scrunch/pull/147

**Comment by mathiasbc** [comment]
Updated documentation: https://github.com/Crunch-io/scrunch/wiki/Multitable-API
