### ISSUE TITLE
Support for applying logical operators on subvars recodes (from multiple responses).

### ISSUE THREAD

**Issue by mohgov** [Crunch-io/scrunch#81]
Requesting options to apply '`not`' to `'has_any()'` method on a multiple response sub variable. Maybe any other operators that might be needed in the future.

Below is example of the recode I was trying to create. The code - `'not(services_new.has_any([2]))'` was where the expression would fail, giving me a Value Error.

`test = fk.create_categorical([
    {'id': 1, 'name': 'NTM for BB', 'case': 'not(services_new.has_any([2])) and bb_main in [r(1,7),17,21,22,96,98] and bb_past not in [1,2,3,4,5,6,7,17,21,22,96,98]'}
], alias='BB_NTM', name='BB_NTM', description='', multiple=False)`

**Comment by dmonroy** [comment]
Valid method name for scrunch is `var.any(...)`, the `var.has_any(...)` is not valid. 

Logical operators are valid on subvars recodes, using either `not(var.any([...]))` or `not var.any([...])`
