### ISSUE TITLE
Create/share dataset filters

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#82]
We need a way to create, publish and generally manage filters that are accessible through the UI.

Example use cases:

```python
ds.add_filter(name="ABC1", expr="social_grade in [1, 2, 3]", public=False)
ds.filters["ABC1"].public = True
ds.filters["ABC1"].remove()
```

**Comment by mathiasbc** [comment]
Implemented here: https://github.com/Crunch-io/scrunch/pull/84

For editing a filter attributes I added the method `edit` to keep compliance with the rest of the code. 

`ds.filters["ABC1"].edit(public=True)`
`ds.filters["ABC1"].edit(expression='var2 == 4')`

**Comment by xbito** [comment]
Done, merged the pull request.
