### ISSUE TITLE
Support for the Crunch Decks API

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#85]
Add helper/s to extend the tables/decks API to scrunch. A general overview of this would include:

* Build new table (assign side/top variables)
* Manage a deck (create, add to, remove from, save, share, etc.)
* Render a table as pandas DataFrame or a deck as a dict of pandas DataFrames
* Export decks to local XLSX

API reference for this is in Crunch: http://docs.crunch.io/#decks

We'll need API support for JSON output of deck contents — that isn't currently in the Crunch API.

**Comment by mathiasbc** [comment]
To make it easier to track the progress of this: https://github.com/Crunch-io/scrunch/pull/110

**Comment by mathiasbc** [comment]
A Dataset can have many Decks, created by the user and a Deck contains Slides (many) and a Slide finally can hold many Analyses. An Analysis in particular is metadata to generate a cube query. For the moment crunch only allows one Slide per Deck and one Analysis por Slide, so a Deck can be thought of as a direct cube query.

**Comment by jjdelc** [comment]
Made a few comment on the PR

**Comment by mathiasbc** [comment]
This is merged, Cube queries are on a different ticket.
