### ISSUE TITLE
Cube queries

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#88]
We need the ability to make ad hoc aggregation requests against the Crunch API using cube queries. Solving this is a precursor to addressing #85.

See the Crunch API docs at: http://docs.crunch.io/?http#multidimensional-analysis

@nealrichardson has advised there are two pieces to work out: (1) the scrunch interface for making cube requests, and (2) working with cube responses (display, slicing, percentaging, etc.).

**Comment by mathiasbc** [comment]
I'm adding more information I gathered from a conversation with Mike Malecki.
https://yougov.slack.com/archives/D34M683FS/p1494946177443002

**Comment by xbito** [comment]
Now that https://github.com/Crunch-io/crunch-cube exists, do we want to integrate? Or just close this ticket?

**Comment by jamesrkg** [comment]
I think we close this one and deal with specific integrations separately.
